// Privé — Love Personality (Tier A redesign, 2026-05-24)
//
// Scientifically-grounded personality system replacing the previous
// 8-question MBTI-clone. Combines two validated instruments:
//
//   • Big Five / OCEAN  — short-form BFI-10
//     (Rammstedt & John, 2007, J. Research in Personality 41:203-212).
//     10 items, 2 per dimension, half reverse-keyed, 5-point Likert.
//
//   • Attachment Theory — Bartholomew & Horowitz Relationship Questionnaire
//     (1991). 4 items, one per style, each rated 5-point "how well does
//     this describe you". Primary style = highest rating; ties resolved
//     in favor of more relationally-functional styles.
//
// The user-facing reveal ("Your Love Personality") is generated per-user
// by Claude (see supabase/functions/ai-love-personality-reveal, Phase 3)
// — every reveal is unique, grounded in the real scores. Internally we
// surface Neuroticism as its inverse (Emotional Stability) so the brand
// language stays positive; scoring math still computes raw N first.

import type { AppLanguage } from '../domain'

// ── Types ───────────────────────────────────────────────────────────

/** 5-point Likert response: 1=Strongly disagree, 5=Strongly agree. */
export type LikertAnswer = 1 | 2 | 3 | 4 | 5

/** Continuous 0–100 scores for the five Big Five dimensions. */
export type BigFiveScores = {
  openness: number
  conscientiousness: number
  extraversion: number
  agreeableness: number
  /** Raw Neuroticism score. UI surfaces (100 - neuroticism) as Emotional Stability. */
  neuroticism: number
}

/** Adult attachment style — four categories from Bartholomew-Horowitz. */
export type AttachmentStyle = 'secure' | 'anxious' | 'avoidant' | 'disorganized'

/** Raw 1–5 ratings for each attachment description (one item per style). */
export type AttachmentRatings = {
  secure: LikertAnswer
  anxious: LikertAnswer
  avoidant: LikertAnswer
  disorganized: LikertAnswer
}

/** The user-facing reveal generated by Claude. Cached on the SelfProfile. */
export type LovePersonalityReveal = {
  archetypeName: string  // e.g., "Curious Anchor" — 2-3 words, poetic
  headline: string       // one resonant sentence
  description: string    // 3-4 short paragraphs
  strengths: string[]    // 3 short phrases
  growthEdges: string[]  // 2 short phrases (compassionate framing)
  language: 'en' | 'ro'
  generatedAt: string    // ISO timestamp
}

/** The full Love Personality stored on the profile. */
export type LovePersonality = {
  bigFive: BigFiveScores
  attachment: AttachmentStyle
  attachmentRatings: AttachmentRatings
  completedAt: string  // ISO timestamp
  reveal?: LovePersonalityReveal  // optional cached Claude output
}

/** A single quiz question shown to the user. */
export type PersonalityQuestion = {
  id: number
  /** What this item measures: a Big Five dimension or an attachment style. */
  measures:
    | { type: 'bigFive'; dimension: keyof BigFiveScores; reverse: boolean }
    | { type: 'attachment'; style: AttachmentStyle }
  /** Stem text shown above the Likert scale. */
  prompt: string
}

// ── The 14 questions ────────────────────────────────────────────────
//
// IMPORTANT: do not casually re-word these. The English wording is the
// validated BFI-10 (Rammstedt & John, 2007) and RQ (Bartholomew & Horowitz,
// 1991) — changing the wording invalidates the psychometric grounding.
// The Romanian translations preserve meaning faithfully.
//
// UI framing (section headers, stem text, transitions) lives in uiText.ts
// and can be styled cinematically — only the per-item prompt is sacred.

const buildEnQuestions = (): PersonalityQuestion[] => [
  // BFI-10 (Rammstedt & John, 2007). Original wording uses the stem "I see
  // myself as someone who [is reserved]"; we rewrite as complete first-person
  // sentences so each prompt reads cleanly on its own card without needing a
  // stem above it. Psychometric meaning preserved — many BFI variants in the
  // wild use exactly this first-person phrasing.
  { id: 1,  measures: { type: 'bigFive', dimension: 'extraversion',      reverse: true  }, prompt: "I'm reserved" },
  { id: 2,  measures: { type: 'bigFive', dimension: 'agreeableness',     reverse: false }, prompt: "I'm generally trusting of people" },
  { id: 3,  measures: { type: 'bigFive', dimension: 'conscientiousness', reverse: true  }, prompt: 'I tend to be lazy' },
  { id: 4,  measures: { type: 'bigFive', dimension: 'neuroticism',       reverse: true  }, prompt: "I'm relaxed and handle stress well" },
  { id: 5,  measures: { type: 'bigFive', dimension: 'openness',          reverse: true  }, prompt: 'I have few artistic interests' },
  { id: 6,  measures: { type: 'bigFive', dimension: 'extraversion',      reverse: false }, prompt: "I'm outgoing and sociable" },
  { id: 7,  measures: { type: 'bigFive', dimension: 'agreeableness',     reverse: true  }, prompt: 'I tend to find fault with others' },
  { id: 8,  measures: { type: 'bigFive', dimension: 'conscientiousness', reverse: false }, prompt: 'I do a thorough job' },
  { id: 9,  measures: { type: 'bigFive', dimension: 'neuroticism',       reverse: false }, prompt: 'I get nervous easily' },
  { id: 10, measures: { type: 'bigFive', dimension: 'openness',          reverse: false }, prompt: 'I have an active imagination' },
  // Attachment — stem in the UI: "How well does this describe how you feel in close relationships?"
  { id: 11, measures: { type: 'attachment', style: 'secure' },
    prompt: "It's easy for me to get close to others. I'm comfortable depending on them and having them depend on me. I don't worry about being alone or about being rejected." },
  { id: 12, measures: { type: 'attachment', style: 'anxious' },
    prompt: 'I want to be very close to others, but I often feel they are reluctant to get as close as I would like. I worry a lot about whether my partner truly loves me or wants to stay.' },
  { id: 13, measures: { type: 'attachment', style: 'avoidant' },
    prompt: 'I am comfortable without close emotional relationships. Independence and self-sufficiency matter to me, and I prefer not to depend on others or have others depend on me.' },
  { id: 14, measures: { type: 'attachment', style: 'disorganized' },
    prompt: "I want close relationships, but I find it hard to fully trust others or to depend on them. I sometimes worry I'll be hurt if I let myself get too close." },
]

const buildRoQuestions = (): PersonalityQuestion[] => [
  // BFI-10 (RO) — rewritten as first-person complete sentences to match the EN
  // version. Same psychometric meaning as the original third-person + stem.
  { id: 1,  measures: { type: 'bigFive', dimension: 'extraversion',      reverse: true  }, prompt: 'Sunt rezervat' },
  { id: 2,  measures: { type: 'bigFive', dimension: 'agreeableness',     reverse: false }, prompt: 'Am încredere în ceilalți' },
  { id: 3,  measures: { type: 'bigFive', dimension: 'conscientiousness', reverse: true  }, prompt: 'Tind să fiu leneș' },
  { id: 4,  measures: { type: 'bigFive', dimension: 'neuroticism',       reverse: true  }, prompt: 'Sunt relaxat și gestionez bine stresul' },
  { id: 5,  measures: { type: 'bigFive', dimension: 'openness',          reverse: true  }, prompt: 'Am puține interese artistice' },
  { id: 6,  measures: { type: 'bigFive', dimension: 'extraversion',      reverse: false }, prompt: 'Sunt extrovertit și sociabil' },
  { id: 7,  measures: { type: 'bigFive', dimension: 'agreeableness',     reverse: true  }, prompt: 'Tind să găsesc defecte la alții' },
  { id: 8,  measures: { type: 'bigFive', dimension: 'conscientiousness', reverse: false }, prompt: 'Fac o treabă temeinică' },
  { id: 9,  measures: { type: 'bigFive', dimension: 'neuroticism',       reverse: false }, prompt: 'Mă enervez ușor' },
  { id: 10, measures: { type: 'bigFive', dimension: 'openness',          reverse: false }, prompt: 'Am o imaginație activă' },
  // Attachment (RO) — stem: "Cât de bine te descrie asta în relațiile apropiate?"
  { id: 11, measures: { type: 'attachment', style: 'secure' },
    prompt: 'Îmi este ușor să mă apropii de alții. Mă simt confortabil să depind de ei și ca ei să depindă de mine. Nu mă îngrijorează singurătatea sau respingerea.' },
  { id: 12, measures: { type: 'attachment', style: 'anxious' },
    prompt: 'Vreau să fiu foarte aproape de alții, dar deseori simt că ei sunt mai reținuți decât mi-aș dori. Mă îngrijorează mult dacă partenerul mă iubește cu adevărat sau dacă va rămâne.' },
  { id: 13, measures: { type: 'attachment', style: 'avoidant' },
    prompt: 'Mă simt bine fără relații emoționale apropiate. Independența contează mult pentru mine și prefer să nu depind de alții sau ca alții să depindă de mine.' },
  { id: 14, measures: { type: 'attachment', style: 'disorganized' },
    prompt: 'Îmi doresc relații apropiate, dar îmi este greu să am încredere deplină în alții sau să depind de ei. Uneori mă tem că voi fi rănit dacă mă apropii prea mult.' },
]

const EN_QUESTIONS = buildEnQuestions()
const RO_QUESTIONS = buildRoQuestions()

/** Always returns 14 questions in stable id order. */
export const getPersonalityQuestions = (language: AppLanguage): PersonalityQuestion[] =>
  language === 'ro' ? RO_QUESTIONS : EN_QUESTIONS

/** Number of questions in the assessment (10 Big Five + 4 attachment). */
export const PERSONALITY_QUESTION_COUNT = 14
export const BIG_FIVE_QUESTION_COUNT = 10
export const ATTACHMENT_QUESTION_COUNT = 4

// ── Scoring ─────────────────────────────────────────────────────────

const reverse = (x: LikertAnswer): number => 6 - x // 5-point reverse-key

const likertToScore0to100 = (avg: number): number =>
  // Map mean Likert (1..5) to 0..100. (avg - 1) * 25 → 0..100.
  Math.max(0, Math.min(100, Math.round((avg - 1) * 25)))

/**
 * Compute Big Five scores from the first 10 Likert answers.
 * Returns 0..100 per dimension. Missing/invalid input yields a neutral 50.
 */
export const bigFiveFromAnswers = (answers: LikertAnswer[]): BigFiveScores => {
  // For each BFI-10 item, get the raw rating; if absent → neutral 3 (Neutral).
  const a = (id: number): LikertAnswer => {
    const v = answers[id - 1]
    return v === 1 || v === 2 || v === 3 || v === 4 || v === 5 ? v : 3
  }
  const avg = (x: number, y: number) => (x + y) / 2

  // BFI-10 dimension recipes (Rammstedt & John, 2007):
  //   Openness          = avg( reverse(Q5),  Q10 )
  //   Conscientiousness = avg( reverse(Q3),  Q8  )
  //   Extraversion      = avg( reverse(Q1),  Q6  )
  //   Agreeableness     = avg( Q2,  reverse(Q7) )
  //   Neuroticism       = avg( reverse(Q4), Q9  )

  return {
    openness:          likertToScore0to100(avg(reverse(a(5)),  a(10))),
    conscientiousness: likertToScore0to100(avg(reverse(a(3)),  a(8))),
    extraversion:      likertToScore0to100(avg(reverse(a(1)),  a(6))),
    agreeableness:     likertToScore0to100(avg(a(2),           reverse(a(7)))),
    neuroticism:       likertToScore0to100(avg(reverse(a(4)),  a(9))),
  }
}

/**
 * Determine primary attachment style from the four ratings.
 * Highest rating wins; ties broken in order: secure > anxious > avoidant > disorganized
 * (favouring the more relationally-functional style on equal scores).
 */
export const attachmentFromRatings = (ratings: AttachmentRatings): AttachmentStyle => {
  const order: AttachmentStyle[] = ['secure', 'anxious', 'avoidant', 'disorganized']
  let best: AttachmentStyle = 'secure'
  let bestScore = -Infinity
  for (const style of order) {
    if (ratings[style] > bestScore) {
      bestScore = ratings[style]
      best = style
    }
  }
  return best
}

/**
 * Build the full LovePersonality struct from the 14 Likert answers.
 * Indices 0-9 are BFI-10; indices 10-13 are the four attachment items
 * (in order: secure, anxious, avoidant, disorganized).
 */
export const lovePersonalityFromAnswers = (
  answers: LikertAnswer[],
): LovePersonality | null => {
  if (!Array.isArray(answers) || answers.length !== PERSONALITY_QUESTION_COUNT) {
    return null
  }
  const bigFive = bigFiveFromAnswers(answers.slice(0, BIG_FIVE_QUESTION_COUNT))
  const attachmentRatings: AttachmentRatings = {
    secure: answers[10],
    anxious: answers[11],
    avoidant: answers[12],
    disorganized: answers[13],
  }
  return {
    bigFive,
    attachment: attachmentFromRatings(attachmentRatings),
    attachmentRatings,
    completedAt: new Date().toISOString(),
  }
}

// ── Compatibility ──────────────────────────────────────────────────

/**
 * 4×4 attachment compatibility matrix from dyadic attachment research.
 * Secure pairings do best; anxious-avoidant the classic doomed pair.
 * Values are 0–100. Symmetric — order doesn't matter.
 */
const ATTACHMENT_COMPAT: Record<AttachmentStyle, Record<AttachmentStyle, number>> = {
  secure: {        secure: 95, anxious: 80, avoidant: 75, disorganized: 70 },
  anxious: {       secure: 80, anxious: 55, avoidant: 35, disorganized: 45 },
  avoidant: {      secure: 75, anxious: 35, avoidant: 50, disorganized: 45 },
  disorganized: {  secure: 70, anxious: 45, avoidant: 45, disorganized: 40 },
}

const BIG_FIVE_KEYS: (keyof BigFiveScores)[] = [
  'openness', 'conscientiousness', 'extraversion', 'agreeableness', 'neuroticism',
]

/**
 * Cosine similarity of two Big Five vectors, rescaled to 0–100.
 * Big Five similarity correlates positively (modestly) with relationship
 * satisfaction; see Luo & Klohnen 2005 and meta-analyses since.
 */
const bigFiveSimilarity = (a: BigFiveScores, b: BigFiveScores): number => {
  let dot = 0
  let magA = 0
  let magB = 0
  for (const k of BIG_FIVE_KEYS) {
    dot += a[k] * b[k]
    magA += a[k] * a[k]
    magB += b[k] * b[k]
  }
  if (magA === 0 || magB === 0) return 50
  const cos = dot / (Math.sqrt(magA) * Math.sqrt(magB))
  // Cosine on positive vectors is in [0,1]; rescale to a usable range.
  // Map [0.7, 1.0] → [40, 95] (typical observed range; complete dissimilarity
  // is rare in real personality data).
  return Math.max(0, Math.min(100, Math.round((cos - 0.7) / 0.3 * 55 + 40)))
}

/**
 * Compatibility score (0–100) between two Love Personalities.
 * Blends:
 *   55% Big Five cosine similarity
 *   45% Attachment dyadic compatibility (lookup matrix)
 * Returns 50 when data is missing for either side.
 */
export const compatibilityFromLovePersonality = (
  mine: LovePersonality | null | undefined,
  theirs: LovePersonality | null | undefined,
): number => {
  if (!mine || !theirs) return 50
  return compatibilityFromBigFiveAttachment(
    mine.bigFive,
    mine.attachment,
    theirs.bigFive,
    theirs.attachment,
  )
}

/**
 * Same blend as compatibilityFromLovePersonality but works on the raw
 * public-derived fields stored on remote Profile rows (bigFive +
 * attachmentStyle), where we don't have the local LovePersonality
 * wrapper / reveal text. Returns 50 if either side is missing data.
 */
export const compatibilityFromBigFiveAttachment = (
  mineBigFive: BigFiveScores | null | undefined,
  mineAttachment: AttachmentStyle | null | undefined,
  theirsBigFive: BigFiveScores | null | undefined,
  theirsAttachment: AttachmentStyle | null | undefined,
): number => {
  if (!mineBigFive || !mineAttachment || !theirsBigFive || !theirsAttachment) return 50
  const b5 = bigFiveSimilarity(mineBigFive, theirsBigFive)
  const att = ATTACHMENT_COMPAT[mineAttachment][theirsAttachment]
  return Math.max(1, Math.min(99, Math.round(b5 * 0.55 + att * 0.45)))
}
