/* cSpell:disable */
export const UI_TEXT = {
  en: {
    nav: {
      discover: 'Discover',
      activity: 'Activity',
      circles: 'Circles',
      chats: 'Chats',
      moderation: 'Moderation',
      profile: 'Profile',
      settings: 'Settings',
    },
    auth: {
      signInTitle: 'Sign in to LoveDate',
      createTitle: 'Create your LoveDate account',
      inviteCode: 'Beta Invite Code',
      invitePlaceholder: 'Enter your invite code',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      passwordHint: 'Use at least 10 chars with uppercase, lowercase, number, and symbol.',
      pleaseWait: 'Please wait...',
      createAccount: 'Create Account',
      signIn: 'Sign In',
      continueGuest: 'Continue as Guest',
      switchToCreate: 'Create account',
      switchToLogin: 'I already have an account',
      language: 'App Language',
      english: 'English',
      romanian: 'Romanian',
    },
    common: {
      exitToLogin: 'Exit to Login',
      backToDiscover: 'Back to Discover',
      loading: 'Loading',
      error: 'Error',
      retry: 'Retry',
      noResults: 'No Results',
      reset: 'Reset',
      saveStatus: 'saved',
      savingStatus: 'saving',
      idleStatus: 'idle',
      errorStatus: 'error',
    },
    discover: {
      summary: 'Discover summary',
      inDeck: 'In Deck',
      matches: 'Matches',
      likesLeft: 'Likes Left',
      superLikes: 'Super Likes',
      openFilters: 'Open Filters',
      boost: 'Boost',
      resetFilters: 'Reset Filters',
      findingProfiles: 'Finding profiles near you...',
      noProfilesMatch: 'No profiles match your filters',
      upNext: 'Up Next',
      activeNow: 'Active now',
      zodiac: 'Zodiac',
      matchScore: 'Match score',
      personality: 'Personality',
      chemistry: 'Chemistry',
      cognitiveOverlap: 'Cognitive overlap',
      aligned: 'Aligned',
      neutral: 'Neutral',
      viewFullProfile: 'View full profile',
      pass: 'Pass',
      superLike: 'Super Like',
      like: 'Like',
      keyboardShortcuts: 'Keyboard shortcuts',
      undoHint: 'U (undo), Esc (close match).',
      likeLimitReached: 'Like limit reached for your current plan.',
      superLikeLimitReached: 'Super Like limit reached for this week.',
      checkingMatch: 'Checking for a match...',
      lastAction: 'Last action',
      deckComplete: 'Deck Complete',
      noMoreProfiles: 'No more profiles for these filters',
      startAgain: 'Start Again',
      clearHistory: 'Clear History',
    },
    settings: {
      controlCenter: 'Control Center',
      title: 'Settings',
      subtitle: 'Manage preferences, sharing, notifications, and safety from one polished dashboard.',
      profileSync: 'Profile sync',
      settingsSync: 'Settings sync',
      connectedSocials: 'Connected socials',
      unreadAlerts: 'Unread alerts',
      preferences: 'Preferences',
      pushNotifications: 'Push Notifications',
      emailNotifications: 'Email Notifications',
      appLanguage: 'App Language',
      syncLine: 'Settings: {settings} • Preferences sync: {preferences}',
      socialTitle: 'Social Connect & Share',
      socialConnectedCount: 'Connected: {count} / {total}',
      socialSimpleMode: 'Simple mode: for each platform, just pick Yes or No.',
      socialPromptOptIn: 'Prompt me to share LoveDate socially',
      socialConnected: 'Connected',
      socialNotConnected: 'Not connected',
      socialConnectAccount: 'Connect this account (Yes)',
      socialShare: 'Share LoveDate',
      planTitle: 'Plan & Session',
      planLabel: 'Plan',
      planLikesUsed: 'Likes used',
      planSuperLikesUsed: 'Super Likes used',
      planBoostsLeft: 'Boosts left',
      planRewindsLeft: 'Rewinds left',
      planPassportAccess: 'Passport access',
      planEnabled: 'Enabled',
      planUpgradeRequired: 'Upgrade required',
      planUnlimited: 'Unlimited',
      planBackendMode: 'Backend mode',
      planSessionNote: 'Sign out and Exit App live in the top header.',
      notificationsTitle: 'Notifications',
      noNotifications: 'No notifications yet.',
      markAllRead: 'Mark all as read',
      safetyTitle: 'Safety',
      blockedProfiles: 'Blocked profiles',
      reportsSubmitted: 'Reports submitted',
      openReports: 'Open reports',
      noReports: 'No safety reports yet.',
      openModeration: 'Open Moderation Center',
    },
    activity: {
      overview: 'Activity overview',
      liked: 'Liked',
      passed: 'Passed',
      matches: 'Matches',
      noMatchesYet: 'No matches yet.',
      noLikesYet: 'No likes yet.',
      noPassesYet: 'No passes yet.',
      chat: 'Chat',
      view: 'View',
    },
    circles: {
      community: 'Circles community',
      title: 'Circles',
      subtitle: 'Join communities around interests and personality vibes.',
      search: 'Search circles',
      searchPlaceholder: 'Design, travel, coffee...',
      members: 'members',
      joined: 'Joined',
      explore: 'Explore',
      leaveCircle: 'Leave Circle',
      joinCircle: 'Join Circle',
      upcomingEvents: 'Upcoming Events',
      rsvpSaved: 'RSVP Saved',
      rsvp: 'RSVP',
      feed: 'Circle Feed',
      sharePrompt: 'Share something with this circle',
      sharePlaceholder: 'Post a thought, event idea, or question...',
      publishPost: 'Publish Post',
      noPosts: 'No posts yet. Be the first to start the conversation.',
      noCirclesFound: 'No circles found for this search.',
    },
    chats: {
      searchPlaceholder: 'Search conversations...',
      online: 'Online',
      audioCall: 'Audio call',
      videoCall: 'Video call',
      moreOptions: 'More options',
      compatibility: 'Compatibility snapshot',
      type: 'Type',
      zodiac: 'Zodiac',
      cognitive: 'Cognitive',
      unknown: 'Unknown',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      aiCoach: 'AI Date Coach (Beta)',
      thinking: 'Thinking...',
      generateSuggestions: 'Generate suggestions',
      coachEmpty: 'Generate personalized opener ideas based on your chemistry and recent chat context.',
      aiPlanner: 'AI Date Planner (Beta)',
      planning: 'Planning...',
      planDate: 'Plan a date',
      useMessage: 'Use this message',
      plannerEmpty: 'Generate 3 personalized date plan options using your shared interests and chemistry.',
      recentCalls: 'Recent Calls',
      videoCallLabel: 'Video call',
      audioCallLabel: 'Audio call',
      rejoin: 'Rejoin',
      openRoom: 'Open room',
      noCallActivity: 'No call activity with this match yet.',
      olderMessages: 'Show {count} older messages',
      joinCall: 'Join call',
      openExternally: 'Open externally',
      attachmentReady: 'Attachment ready:',
      remove: 'Remove',
      typeMessage: 'Type a message...',
      attachMedia: 'Attach media',
      stopRecording: 'Stop recording',
      recordVoice: 'Record voice',
      send: 'Send',
      noChat: 'No Chat',
      selectMatch: 'Select a match to begin chatting',
      datePlanTonePlayful: 'playful and flirty',
      datePlanToneWarm: 'warm and curious',
      datePlanToneLight: 'light and low-pressure',
      datePlanGoldenTitle: 'Golden Hour Micro-Date',
      datePlanGoldenPlace: '{anchor} + scenic walk',
      datePlanGoldenDuration: '60-90 min',
      datePlanGoldenPitch: 'A {tone} first meetup: a quick {anchor} stop and then a short walk in {city}.',
      datePlanGoldenMessage: 'I have an idea: a {tone} first meetup this week — {anchor} and a short golden-hour walk in {city}. 60-90 minutes, easy vibe. What day works for you?',
      datePlanCultureTitle: 'Culture + Conversation',
      datePlanCulturePlace: 'gallery or museum + {anchorTwo}',
      datePlanCultureDuration: '2-3 hours',
      datePlanCulturePitch: 'A deeper date with conversation moments and shared taste around {anchorTwo}.',
      datePlanCultureMessage: 'Would you be up for a culture date? We could do a gallery/museum stop and then {anchorTwo} after. I think it would fit our vibe really well.',
      datePlanSignatureTitle: 'Signature Night Plan',
      datePlanSignaturePlace: '{anchor} experience + dinner',
      datePlanSignatureDuration: '3-4 hours',
      datePlanSignaturePitch: 'A more curated date flow designed around your chemistry and shared energy.',
      datePlanSignatureMessage: 'I want to plan a proper signature date: start with a {anchor} experience and continue with dinner. If you like, I can send you two concrete options and you pick your favorite.',
    },
    profile: {
      screen: 'Profile screen',
      overview: 'Profile overview',
      aboutMe: 'About Me',
      personalityCode: 'Personality code',
      primary: 'Primary',
      support: 'Support',
      zodiacNote: 'Zodiac note',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      whatCodeMeans: 'What does this code mean?',
      interests: 'Interests',
      socialTrust: 'Social Trust',
      connectedAccounts: 'Connected accounts',
      noSocialAccounts: 'No social accounts connected yet',
      editProfile: 'Edit My Profile',
      identity: 'Identity',
      name: 'Name',
      age: 'Age',
      pronouns: 'Pronouns',
      gender: 'Gender',
      orientation: 'Orientation',
      heightCm: 'Height (cm)',
      profileDetails: 'Profile Details',
      city: 'City',
      hometown: 'Hometown',
      vibe: 'Vibe',
      lookingFor: 'Looking For',
      relationshipIntent: 'Relationship Intent',
      interestsComma: 'Interests (comma separated)',
      bio: 'Bio',
      personalityQuiz: 'Personality Quiz',
      compatibilityCode: 'Compatibility code',
      pickOption: 'Pick the option that fits you best.',
      openGuide: 'Open personality guide',
      careerLifestyle: 'Career And Lifestyle',
      jobTitle: 'Job Title',
      company: 'Company',
      education: 'Education',
      languagesComma: 'Languages (comma separated)',
      drinking: 'Drinking',
      smoking: 'Smoking',
      workout: 'Workout',
      pets: 'Pets',
      childrenPlan: 'Children Plan',
      religion: 'Religion',
      politics: 'Politics',
      zodiac: 'Zodiac',
      promptsSocial: 'Prompts And Social',
      prompt1: 'Prompt 1',
      prompt2: 'Prompt 2',
      prompt3: 'Prompt 3',
      dealbreakersComma: 'Dealbreakers (comma separated)',
      instagram: 'Instagram',
      anthem: 'Anthem',
      travelMode: 'Travel Mode',
      photos: 'Photos',
      pastePhotoUrl: 'Paste photo URL',
      addUrl: 'Add URL',
      uploadPhoto: 'Upload photo (opens editor)',
      primaryPhoto: 'Primary',
      setAsPrimary: 'Set as Primary',
    },
  },
  ro: {
    nav: {
      discover: 'Descoperă',
      activity: 'Activitate',
      circles: 'Cercuri',
      chats: 'Mesaje',
      moderation: 'Moderare',
      profile: 'Profil',
      settings: 'Setări',
    },
    auth: {
      signInTitle: 'Intră în LoveDate',
      createTitle: 'Creează-ți contul LoveDate',
      inviteCode: 'Cod de invitație beta',
      invitePlaceholder: 'Introdu codul de invitație',
      email: 'Email',
      password: 'Parolă',
      confirmPassword: 'Confirmă parola',
      passwordHint: 'Minim 10 caractere — literă mare, literă mică, cifră și simbol.',
      pleaseWait: 'Te rugăm să aștepți...',
      createAccount: 'Creează cont',
      signIn: 'Intră în cont',
      continueGuest: 'Continuă ca invitat',
      switchToCreate: 'Creează cont nou',
      switchToLogin: 'Am deja cont',
      language: 'Limba aplicației',
      english: 'Engleză',
      romanian: 'Română',
    },
    common: {
      exitToLogin: 'Înapoi la autentificare',
      backToDiscover: 'Înapoi la Descoperă',
      loading: 'Se încarcă',
      error: 'Eroare',
      retry: 'Încearcă din nou',
      noResults: 'Niciun rezultat',
      reset: 'Resetează',
      saveStatus: 'salvat',
      savingStatus: 'se salvează',
      idleStatus: 'în așteptare',
      errorStatus: 'eroare',
    },
    discover: {
      summary: 'Rezumat descoperire',
      inDeck: 'Disponibili',
      matches: 'Potriviri',
      likesLeft: 'Aprecieri rămase',
      superLikes: 'Super Aprecieri',
      openFilters: 'Filtre',
      boost: 'Boost',
      resetFilters: 'Resetează filtrele',
      findingProfiles: 'Căutăm profile în apropierea ta...',
      noProfilesMatch: 'Niciun profil nu corespunde filtrelor tale',
      upNext: 'Urmează',
      activeNow: 'Activă acum',
      zodiac: 'Zodie',
      matchScore: 'Scor de compatibilitate',
      personality: 'Personalitate',
      chemistry: 'Chimie',
      cognitiveOverlap: 'Suprapunere cognitivă',
      aligned: 'În armonie',
      neutral: 'Neutru',
      viewFullProfile: 'Vezi profilul complet',
      pass: 'Treci',
      superLike: 'Super Apreciere',
      like: 'Apreciere',
      keyboardShortcuts: 'Scurtături tastatură',
      undoHint: 'U (revino), Esc (închide potrivirea).',
      likeLimitReached: 'Ai atins limita de aprecieri pentru planul tău.',
      superLikeLimitReached: 'Ai atins limita de Super Aprecieri pentru săptămâna asta.',
      checkingMatch: 'Verificăm dacă e potrivire...',
      lastAction: 'Ultima acțiune',
      deckComplete: 'Ai văzut tot ce era disponibil',
      noMoreProfiles: 'Nu mai sunt profile care să corespundă filtrelor',
      startAgain: 'Începe din nou',
      clearHistory: 'Șterge istoricul',
    },
    settings: {
      controlCenter: 'Centru de control',
      title: 'Setări',
      subtitle: 'Gestionează preferințele, distribuirea, notificările și siguranța dintr-un singur panou elegant.',
      profileSync: 'Sincronizare profil',
      settingsSync: 'Sincronizare setări',
      connectedSocials: 'Rețele conectate',
      unreadAlerts: 'Alerte necitite',
      preferences: 'Preferințe',
      pushNotifications: 'Notificări push',
      emailNotifications: 'Notificări email',
      appLanguage: 'Limba aplicației',
      syncLine: 'Setări: {settings} • Sincronizare preferințe: {preferences}',
      socialTitle: 'Rețele sociale și distribuire',
      socialConnectedCount: 'Conectate: {count} / {total}',
      socialSimpleMode: 'Mod simplu: pentru fiecare rețea, alegi Da sau Nu.',
      socialPromptOptIn: 'Întreabă-mă să distribui LoveDate pe rețele',
      socialConnected: 'Conectat',
      socialNotConnected: 'Neconectat',
      socialConnectAccount: 'Conectează acest cont (Da)',
      socialShare: 'Distribuie LoveDate',
      planTitle: 'Plan și sesiune',
      planLabel: 'Plan',
      planLikesUsed: 'Aprecieri folosite',
      planSuperLikesUsed: 'Super aprecieri folosite',
      planBoostsLeft: 'Boost-uri rămase',
      planRewindsLeft: 'Întoarceri rămase',
      planPassportAccess: 'Acces Passport',
      planEnabled: 'Activ',
      planUpgradeRequired: 'Necesită upgrade',
      planUnlimited: 'Nelimitat',
      planBackendMode: 'Mod backend',
      planSessionNote: 'Deconectarea și ieșirea din aplicație sunt în bara de sus.',
      notificationsTitle: 'Notificări',
      noNotifications: 'Nu ai încă notificări.',
      markAllRead: 'Marchează tot ca citit',
      safetyTitle: 'Siguranță',
      blockedProfiles: 'Profiluri blocate',
      reportsSubmitted: 'Raportări trimise',
      openReports: 'Raportări deschise',
      noReports: 'Nu există încă raportări de siguranță.',
      openModeration: 'Deschide centrul de moderare',
    },
    activity: {
      overview: 'Prezentare activitate',
      liked: 'Apreciate',
      passed: 'Respinse',
      matches: 'Potriviri',
      noMatchesYet: 'Nu ai încă potriviri.',
      noLikesYet: 'Nu ai încă aprecieri.',
      noPassesYet: 'Nu ai încă respingeri.',
      chat: 'Chat',
      view: 'Vezi',
    },
    circles: {
      community: 'Comunitatea cercurilor',
      title: 'Cercuri',
      subtitle: 'Intră în comunități construite în jurul intereselor și al vibrației de personalitate.',
      search: 'Caută cercuri',
      searchPlaceholder: 'Design, călătorii, cafea...',
      members: 'membri',
      joined: 'Membru',
      explore: 'Explorează',
      leaveCircle: 'Părăsește cercul',
      joinCircle: 'Alătură-te cercului',
      upcomingEvents: 'Evenimente viitoare',
      rsvpSaved: 'RSVP salvat',
      rsvp: 'RSVP',
      feed: 'Fluxul cercului',
      sharePrompt: 'Spune ceva acestui cerc',
      sharePlaceholder: 'Publică un gând, o idee de eveniment sau o întrebare...',
      publishPost: 'Publică postarea',
      noPosts: 'Nu există încă postări. Fii primul care începe conversația.',
      noCirclesFound: 'Nu au fost găsite cercuri pentru această căutare.',
    },
    chats: {
      searchPlaceholder: 'Caută în conversații...',
      online: 'Online',
      audioCall: 'Apel audio',
      videoCall: 'Apel video',
      moreOptions: 'Mai multe opțiuni',
      compatibility: 'Rezumat compatibilitate',
      type: 'Tip',
      zodiac: 'Zodie',
      cognitive: 'Cognitiv',
      unknown: 'Necunoscut',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      aiCoach: 'Asistent AI pentru conversație (Beta)',
      thinking: 'Se gândește...',
      generateSuggestions: 'Sugerează mesaje',
      coachEmpty: 'Idei personalizate de început de conversație, pe baza chimiei voastre și a mesajelor recente.',
      aiPlanner: 'Planificator AI de întâlniri (Beta)',
      planning: 'Se planifică...',
      planDate: 'Planifică o întâlnire',
      useMessage: 'Folosește acest text',
      plannerEmpty: '3 idei personalizate de întâlnire, plecând de la interesele și chimia voastră.',
      recentCalls: 'Apeluri recente',
      videoCallLabel: 'Apel video',
      audioCallLabel: 'Apel audio',
      rejoin: 'Reintră',
      openRoom: 'Deschide camera',
      noCallActivity: 'Niciun apel încă cu această persoană.',
      olderMessages: 'Arată {count} mesaje mai vechi',
      joinCall: 'Intră în apel',
      openExternally: 'Deschide extern',
      attachmentReady: 'Atașament pregătit:',
      remove: 'Elimină',
      typeMessage: 'Scrie un mesaj...',
      attachMedia: 'Atașează un fișier',
      stopRecording: 'Oprește înregistrarea',
      recordVoice: 'Înregistrează o notă vocală',
      send: 'Trimite',
      noChat: 'Nicio conversație',
      selectMatch: 'Alege o potrivire ca să începi conversația',
      datePlanTonePlayful: 'jucăușă și cochetă',
      datePlanToneWarm: 'caldă și curioasă',
      datePlanToneLight: 'lejeră și fără presiune',
      datePlanGoldenTitle: 'Întâlnire scurtă la apus',
      datePlanGoldenPlace: '{anchor} + plimbare pitorească',
      datePlanGoldenDuration: '60-90 min',
      datePlanGoldenPitch: 'O primă întâlnire {tone}: o oprire scurtă pentru {anchor} și apoi o plimbare scurtă în {city}.',
      datePlanGoldenMessage: 'Am o idee: o primă întâlnire {tone} săptămâna asta — {anchor} și o plimbare scurtă la apus în {city}. 60-90 minute, lejer. Ce zi îți convine?',
      datePlanCultureTitle: 'Cultură și conversație',
      datePlanCulturePlace: 'galerie sau muzeu + {anchorTwo}',
      datePlanCultureDuration: '2-3 ore',
      datePlanCulturePitch: 'O întâlnire mai profundă, cu momente de conversație și gust comun pentru {anchorTwo}.',
      datePlanCultureMessage: 'Ai chef de o întâlnire culturală? Putem trece pe la o galerie sau un muzeu și apoi {anchorTwo}. Cred că s-ar potrivi vibe-ului nostru.',
      datePlanSignatureTitle: 'Plan de seară',
      datePlanSignaturePlace: 'experiență {anchor} + cină',
      datePlanSignatureDuration: '3-4 ore',
      datePlanSignaturePitch: 'O întâlnire mai elaborată, gândită în jurul chimiei și energiei voastre comune.',
      datePlanSignatureMessage: 'Vreau să planific o întâlnire ca lumea: începem cu o experiență {anchor} și continuăm cu o cină. Dacă vrei, îți pot trimite două variante concrete, iar tu alegi.',
    },
    profile: {
      screen: 'Profil',
      overview: 'Prezentare profil',
      aboutMe: 'Despre mine',
      personalityCode: 'Codul tău de personalitate',
      primary: 'Principal',
      support: 'Auxiliar',
      zodiacNote: 'Notă zodiacală',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      whatCodeMeans: 'Ce înseamnă acest cod?',
      interests: 'Interese',
      socialTrust: 'Încredere socială',
      connectedAccounts: 'Conturi conectate',
      noSocialAccounts: 'Nu ai încă niciun cont social conectat',
      editProfile: 'Editează profilul',
      identity: 'Identitate',
      name: 'Nume',
      age: 'Vârstă',
      pronouns: 'Pronume',
      gender: 'Gen',
      orientation: 'Orientare',
      heightCm: 'Înălțime (cm)',
      profileDetails: 'Detalii profil',
      city: 'Oraș',
      hometown: 'Oraș natal',
      vibe: 'Vibe',
      lookingFor: 'Caut',
      relationshipIntent: 'Intenția relației',
      interestsComma: 'Interese (separate prin virgulă)',
      bio: 'Bio',
      personalityQuiz: 'Test de personalitate',
      compatibilityCode: 'Cod de compatibilitate',
      pickOption: 'Alege varianta care te descrie cel mai bine.',
      openGuide: 'Deschide ghidul de personalitate',
      careerLifestyle: 'Carieră și stil de viață',
      jobTitle: 'Funcție',
      company: 'Companie',
      education: 'Educație',
      languagesComma: 'Limbi vorbite (separate prin virgulă)',
      drinking: 'Alcool',
      smoking: 'Fumat',
      workout: 'Sport',
      pets: 'Animale',
      childrenPlan: 'Plan pentru copii',
      religion: 'Religie',
      politics: 'Politică',
      zodiac: 'Zodie',
      promptsSocial: 'Întrebări și social media',
      prompt1: 'Întrebare 1',
      prompt2: 'Întrebare 2',
      prompt3: 'Întrebare 3',
      dealbreakersComma: 'Lucruri intolerabile (separate prin virgulă)',
      instagram: 'Instagram',
      anthem: 'Cântec preferat',
      travelMode: 'Mod călătorie',
      photos: 'Poze',
      pastePhotoUrl: 'Adaugă un link de poză',
      addUrl: 'Adaugă',
      uploadPhoto: 'Încarcă o poză (deschide editorul)',
      primaryPhoto: 'Principală',
      setAsPrimary: 'Setează ca principală',
    },
  },
} as const
/* cSpell:enable */
