/* cSpell:disable */
export const UI_TEXT = {
  en: {
    nav: {
      discover: 'Discover',
      activity: 'Activity',
      circles: 'Circles',
      chats: 'Chats',
      moderation: 'Moderation',
      profile: 'Profile',
      settings: 'Settings',
    },
    auth: {
      signInTitle: 'Sign in to LoveDate',
      createTitle: 'Create your LoveDate account',
      inviteCode: 'Beta Invite Code',
      invitePlaceholder: 'Enter your invite code',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      passwordHint: 'Use at least 10 chars with uppercase, lowercase, number, and symbol.',
      pleaseWait: 'Please wait...',
      createAccount: 'Create Account',
      signIn: 'Sign In',
      continueGuest: 'Continue as Guest',
      switchToCreate: 'Create account',
      switchToLogin: 'I already have an account',
      language: 'App Language',
      english: 'English',
      romanian: 'Romanian',
    },
    common: {
      exitToLogin: 'Exit to Login',
      backToDiscover: 'Back to Discover',
      loading: 'Loading',
      error: 'Error',
      retry: 'Retry',
      noResults: 'No Results',
      reset: 'Reset',
      saveStatus: 'saved',
      savingStatus: 'saving',
      idleStatus: 'idle',
      errorStatus: 'error',
    },
    discover: {
      summary: 'Discover summary',
      inDeck: 'In Deck',
      matches: 'Matches',
      likesLeft: 'Likes Left',
      superLikes: 'Super Likes',
      openFilters: 'Open Filters',
      boost: 'Boost',
      resetFilters: 'Reset Filters',
      findingProfiles: 'Finding profiles near you...',
      noProfilesMatch: 'No profiles match your filters',
      upNext: 'Up Next',
      activeNow: 'Active now',
      zodiac: 'Zodiac',
      matchScore: 'Match score',
      personality: 'Personality',
      chemistry: 'Chemistry',
      cognitiveOverlap: 'Cognitive overlap',
      aligned: 'Aligned',
      neutral: 'Neutral',
      viewFullProfile: 'View full profile',
      pass: 'Pass',
      superLike: 'Super Like',
      like: 'Like',
      keyboardShortcuts: 'Keyboard shortcuts',
      undoHint: 'U (undo), Esc (close match).',
      likeLimitReached: 'Like limit reached for your current plan.',
      superLikeLimitReached: 'Super Like limit reached for this week.',
      checkingMatch: 'Checking for a match...',
      lastAction: 'Last action',
      deckComplete: 'Deck Complete',
      noMoreProfiles: 'No more profiles for these filters',
      startAgain: 'Start Again',
      clearHistory: 'Clear History',
    },
    settings: {
      controlCenter: 'Control Center',
      title: 'Settings',
      subtitle: 'Manage preferences, sharing, notifications, and safety from one polished dashboard.',
      profileSync: 'Profile sync',
      settingsSync: 'Settings sync',
      connectedSocials: 'Connected socials',
      unreadAlerts: 'Unread alerts',
      preferences: 'Preferences',
      pushNotifications: 'Push Notifications',
      emailNotifications: 'Email Notifications',
      privateMode: 'Private Mode',
      incognitoMode: 'Incognito Mode',
      appLanguage: 'App Language',
      syncLine: 'Settings: {settings} • Preferences sync: {preferences}',
    },
    activity: {
      overview: 'Activity overview',
      liked: 'Liked',
      passed: 'Passed',
      matches: 'Matches',
      noMatchesYet: 'No matches yet.',
      noLikesYet: 'No likes yet.',
      noPassesYet: 'No passes yet.',
      chat: 'Chat',
      view: 'View',
    },
    circles: {
      community: 'Circles community',
      title: 'Circles',
      subtitle: 'Join communities around interests and personality vibes.',
      search: 'Search circles',
      searchPlaceholder: 'Design, travel, coffee...',
      members: 'members',
      joined: 'Joined',
      explore: 'Explore',
      leaveCircle: 'Leave Circle',
      joinCircle: 'Join Circle',
      upcomingEvents: 'Upcoming Events',
      rsvpSaved: 'RSVP Saved',
      rsvp: 'RSVP',
      feed: 'Circle Feed',
      sharePrompt: 'Share something with this circle',
      sharePlaceholder: 'Post a thought, event idea, or question...',
      publishPost: 'Publish Post',
      noPosts: 'No posts yet. Be the first to start the conversation.',
      noCirclesFound: 'No circles found for this search.',
    },
    chats: {
      searchPlaceholder: 'Search conversations...',
      online: 'Online',
      audioCall: 'Audio call',
      videoCall: 'Video call',
      moreOptions: 'More options',
      compatibility: 'Compatibility snapshot',
      type: 'Type',
      zodiac: 'Zodiac',
      cognitive: 'Cognitive',
      unknown: 'Unknown',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      aiCoach: 'AI Date Coach (Beta)',
      thinking: 'Thinking...',
      generateSuggestions: 'Generate suggestions',
      coachEmpty: 'Generate personalized opener ideas based on your chemistry and recent chat context.',
      aiPlanner: 'AI Date Planner (Beta)',
      planning: 'Planning...',
      planDate: 'Plan a date',
      useMessage: 'Use this message',
      plannerEmpty: 'Generate 3 personalized date plan options using your shared interests and chemistry.',
      recentCalls: 'Recent Calls',
      videoCallLabel: 'Video call',
      audioCallLabel: 'Audio call',
      rejoin: 'Rejoin',
      openRoom: 'Open room',
      noCallActivity: 'No call activity with this match yet.',
      olderMessages: 'Show {count} older messages',
      joinCall: 'Join call',
      openExternally: 'Open externally',
      attachmentReady: 'Attachment ready:',
      remove: 'Remove',
      typeMessage: 'Type a message...',
      attachMedia: 'Attach media',
      stopRecording: 'Stop recording',
      recordVoice: 'Record voice',
      send: 'Send',
      noChat: 'No Chat',
      selectMatch: 'Select a match to begin chatting',
    },
    profile: {
      screen: 'Profile screen',
      overview: 'Profile overview',
      aboutMe: 'About Me',
      personalityCode: 'Personality code',
      primary: 'Primary',
      support: 'Support',
      zodiacNote: 'Zodiac note',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      whatCodeMeans: 'What does this code mean?',
      interests: 'Interests',
      socialTrust: 'Social Trust',
      connectedAccounts: 'Connected accounts',
      noSocialAccounts: 'No social accounts connected yet',
      editProfile: 'Edit My Profile',
      identity: 'Identity',
      name: 'Name',
      age: 'Age',
      pronouns: 'Pronouns',
      gender: 'Gender',
      orientation: 'Orientation',
      heightCm: 'Height (cm)',
      profileDetails: 'Profile Details',
      city: 'City',
      hometown: 'Hometown',
      vibe: 'Vibe',
      lookingFor: 'Looking For',
      relationshipIntent: 'Relationship Intent',
      interestsComma: 'Interests (comma separated)',
      bio: 'Bio',
      personalityQuiz: 'Personality Quiz',
      compatibilityCode: 'Compatibility code',
      pickOption: 'Pick the option that fits you best.',
      openGuide: 'Open personality guide',
      careerLifestyle: 'Career And Lifestyle',
      jobTitle: 'Job Title',
      company: 'Company',
      education: 'Education',
      languagesComma: 'Languages (comma separated)',
      drinking: 'Drinking',
      smoking: 'Smoking',
      workout: 'Workout',
      pets: 'Pets',
      childrenPlan: 'Children Plan',
      religion: 'Religion',
      politics: 'Politics',
      zodiac: 'Zodiac',
      promptsSocial: 'Prompts And Social',
      prompt1: 'Prompt 1',
      prompt2: 'Prompt 2',
      prompt3: 'Prompt 3',
      dealbreakersComma: 'Dealbreakers (comma separated)',
      instagram: 'Instagram',
      anthem: 'Anthem',
      travelMode: 'Travel Mode',
      photos: 'Photos',
      pastePhotoUrl: 'Paste photo URL',
      addUrl: 'Add URL',
      uploadPhoto: 'Upload photo (opens editor)',
      primaryPhoto: 'Primary',
      setAsPrimary: 'Set as Primary',
    },
  },
  ro: {
    nav: {
      discover: 'Descoperă',
      activity: 'Activitate',
      circles: 'Cercuri',
      chats: 'Chat-uri',
      moderation: 'Moderare',
      profile: 'Profil',
      settings: 'Setări',
    },
    auth: {
      signInTitle: 'Conectează-te la LoveDate',
      createTitle: 'Creează-ți contul LoveDate',
      inviteCode: 'Cod invitație beta',
      invitePlaceholder: 'Introdu codul de invitație',
      email: 'Email',
      password: 'Parolă',
      confirmPassword: 'Confirmă parola',
      passwordHint: 'Folosește cel puțin 10 caractere cu literă mare, literă mică, număr și simbol.',
      pleaseWait: 'Te rugăm așteaptă...',
      createAccount: 'Creează cont',
      signIn: 'Conectare',
      continueGuest: 'Continuă ca invitat',
      switchToCreate: 'Creează cont',
      switchToLogin: 'Am deja cont',
      language: 'Limba aplicației',
      english: 'Engleză',
      romanian: 'Română',
    },
    common: {
      exitToLogin: 'Ieși la autentificare',
      backToDiscover: 'Înapoi la Descoperă',
      loading: 'Se încarcă',
      error: 'Eroare',
      retry: 'Reîncearcă',
      noResults: 'Fără rezultate',
      reset: 'Resetează',
      saveStatus: 'salvat',
      savingStatus: 'se salvează',
      idleStatus: 'inactiv',
      errorStatus: 'eroare',
    },
    discover: {
      summary: 'Rezumat descoperire',
      inDeck: 'În pachet',
      matches: 'Potriviri',
      likesLeft: 'Like-uri rămase',
      superLikes: 'Super Like-uri',
      openFilters: 'Deschide filtrele',
      boost: 'Promovare',
      resetFilters: 'Resetează filtrele',
      findingProfiles: 'Căutăm profile în apropierea ta...',
      noProfilesMatch: 'Niciun profil nu se potrivește cu filtrele tale',
      upNext: 'Urmează',
      activeNow: 'Activ acum',
      zodiac: 'Zodie',
      matchScore: 'Scor compatibilitate',
      personality: 'Personalitate',
      chemistry: 'Chimie',
      cognitiveOverlap: 'Suprapunere cognitivă',
      aligned: 'Aliniat',
      neutral: 'Neutru',
      viewFullProfile: 'Vezi profilul complet',
      pass: 'Pas',
      superLike: 'Super Like',
      like: 'Like',
      keyboardShortcuts: 'Scurtături tastatură',
      undoHint: 'U (anulează), Esc (închide potrivirea).',
      likeLimitReached: 'Ai atins limita de Like-uri pentru planul tău curent.',
      superLikeLimitReached: 'Ai atins limita de Super Like-uri pentru această săptămână.',
      checkingMatch: 'Verificăm dacă există o potrivire...',
      lastAction: 'Ultima acțiune',
      deckComplete: 'Pachet terminat',
      noMoreProfiles: 'Nu mai există profile pentru aceste filtre',
      startAgain: 'Pornește din nou',
      clearHistory: 'Șterge istoricul',
    },
    settings: {
      controlCenter: 'Centru de control',
      title: 'Setări',
      subtitle: 'Gestionează preferințele, distribuirea, notificările și siguranța dintr-un singur panou elegant.',
      profileSync: 'Sincronizare profil',
      settingsSync: 'Sincronizare setări',
      connectedSocials: 'Rețele conectate',
      unreadAlerts: 'Alerte necitite',
      preferences: 'Preferințe',
      pushNotifications: 'Notificări push',
      emailNotifications: 'Notificări email',
      privateMode: 'Mod privat',
      incognitoMode: 'Mod incognito',
      appLanguage: 'Limba aplicației',
      syncLine: 'Setări: {settings} • Sincronizare preferințe: {preferences}',
    },
    activity: {
      overview: 'Prezentare activitate',
      liked: 'Apreciate',
      passed: 'Respinse',
      matches: 'Potriviri',
      noMatchesYet: 'Nu ai încă potriviri.',
      noLikesYet: 'Nu ai încă aprecieri.',
      noPassesYet: 'Nu ai încă respingeri.',
      chat: 'Chat',
      view: 'Vezi',
    },
    circles: {
      community: 'Comunitatea cercurilor',
      title: 'Cercuri',
      subtitle: 'Intră în comunități construite în jurul intereselor și al vibrației de personalitate.',
      search: 'Caută cercuri',
      searchPlaceholder: 'Design, călătorii, cafea...',
      members: 'membri',
      joined: 'Membru',
      explore: 'Explorează',
      leaveCircle: 'Părăsește cercul',
      joinCircle: 'Alătură-te cercului',
      upcomingEvents: 'Evenimente viitoare',
      rsvpSaved: 'RSVP salvat',
      rsvp: 'RSVP',
      feed: 'Fluxul cercului',
      sharePrompt: 'Spune ceva acestui cerc',
      sharePlaceholder: 'Publică un gând, o idee de eveniment sau o întrebare...',
      publishPost: 'Publică postarea',
      noPosts: 'Nu există încă postări. Fii primul care începe conversația.',
      noCirclesFound: 'Nu au fost găsite cercuri pentru această căutare.',
    },
    chats: {
      searchPlaceholder: 'Caută conversații...',
      online: 'Online',
      audioCall: 'Apel audio',
      videoCall: 'Apel video',
      moreOptions: 'Mai multe opțiuni',
      compatibility: 'Rezumat compatibilitate',
      type: 'Tip',
      zodiac: 'Zodie',
      cognitive: 'Cognitiv',
      unknown: 'Necunoscut',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      aiCoach: 'Antrenor AI pentru întâlniri (Beta)',
      thinking: 'Se gândește...',
      generateSuggestions: 'Generează sugestii',
      coachEmpty: 'Generează idei personalizate de început de conversație pe baza chimiei și a contextului recent din chat.',
      aiPlanner: 'Planificator AI de întâlniri (Beta)',
      planning: 'Planifică...',
      planDate: 'Planifică o întâlnire',
      useMessage: 'Folosește mesajul',
      plannerEmpty: 'Generează 3 opțiuni personalizate de întâlnire folosind interesele și chimia voastră comună.',
      recentCalls: 'Apeluri recente',
      videoCallLabel: 'Apel video',
      audioCallLabel: 'Apel audio',
      rejoin: 'Reintră',
      openRoom: 'Deschide camera',
      noCallActivity: 'Nu există încă activitate de apel cu această potrivire.',
      olderMessages: 'Arată {count} mesaje mai vechi',
      joinCall: 'Intră în apel',
      openExternally: 'Deschide extern',
      attachmentReady: 'Atașament pregătit:',
      remove: 'Elimină',
      typeMessage: 'Scrie un mesaj...',
      attachMedia: 'Atașează media',
      stopRecording: 'Oprește înregistrarea',
      recordVoice: 'Înregistrează voce',
      send: 'Trimite',
      noChat: 'Fără chat',
      selectMatch: 'Selectează o potrivire pentru a începe conversația',
    },
    profile: {
      screen: 'Ecran profil',
      overview: 'Prezentare profil',
      aboutMe: 'Despre mine',
      personalityCode: 'Cod de personalitate',
      primary: 'Principal',
      support: 'Suport',
      zodiacNote: 'Notă zodiacală',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      whatCodeMeans: 'Ce înseamnă acest cod?',
      interests: 'Interese',
      socialTrust: 'Încredere socială',
      connectedAccounts: 'Conturi conectate',
      noSocialAccounts: 'Nu există încă conturi sociale conectate',
      editProfile: 'Editează profilul meu',
      identity: 'Identitate',
      name: 'Nume',
      age: 'Vârstă',
      pronouns: 'Pronume',
      gender: 'Gen',
      orientation: 'Orientare',
      heightCm: 'Înălțime (cm)',
      profileDetails: 'Detalii profil',
      city: 'Oraș',
      hometown: 'Oraș natal',
      vibe: 'Vibe',
      lookingFor: 'Caut',
      relationshipIntent: 'Intenția relației',
      interestsComma: 'Interese (separate prin virgulă)',
      bio: 'Bio',
      personalityQuiz: 'Test de personalitate',
      compatibilityCode: 'Cod de compatibilitate',
      pickOption: 'Alege opțiunea care ți se potrivește cel mai bine.',
      openGuide: 'Deschide ghidul de personalitate',
      careerLifestyle: 'Carieră și stil de viață',
      jobTitle: 'Funcție',
      company: 'Companie',
      education: 'Educație',
      languagesComma: 'Limbi vorbite (separate prin virgulă)',
      drinking: 'Alcool',
      smoking: 'Fumat',
      workout: 'Sport',
      pets: 'Animale',
      childrenPlan: 'Plan pentru copii',
      religion: 'Religie',
      politics: 'Politică',
      zodiac: 'Zodie',
      promptsSocial: 'Prompturi și social',
      prompt1: 'Prompt 1',
      prompt2: 'Prompt 2',
      prompt3: 'Prompt 3',
      dealbreakersComma: 'Dealbreakers (separate prin virgulă)',
      instagram: 'Instagram',
      anthem: 'Imn',
      travelMode: 'Mod călătorie',
      photos: 'Poze',
      pastePhotoUrl: 'Lipește URL-ul pozei',
      addUrl: 'Adaugă URL',
      uploadPhoto: 'Încarcă poză (deschide editorul)',
      primaryPhoto: 'Principală',
      setAsPrimary: 'Setează ca principală',
    },
  },
} as const
/* cSpell:enable */
