/* cSpell:disable */
export const UI_TEXT = {
  en: {
    nav: {
      discover: 'Discover',
      activity: 'Activity',
      circles: 'Circles',
      chats: 'Chats',
      moderation: 'Moderation',
      profile: 'Profile',
      settings: 'Settings',
    },
    auth: {
      signInTitle: 'Sign in to Privé',
      createTitle: 'Create your Privé account',
      inviteCode: 'Invite Code',
      invitePlaceholder: 'Enter your invite code',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      passwordHint: 'Use at least 10 chars with uppercase, lowercase, number, and symbol.',
      pleaseWait: 'Please wait...',
      createAccount: 'Create Account',
      signIn: 'Sign In',
      continueGuest: 'Continue as Guest',
      switchToCreate: 'Create account',
      switchToLogin: 'I already have an account',
      language: 'App Language',
      english: 'English',
      romanian: 'Romanian',
    },
    waitlist: {
      title: 'Request access',
      subtitle: 'Privé is invite-only. Tell us how to reach you.',
      emailLabel: 'Email',
      noteLabel: 'How did you hear about Privé? (optional)',
      submit: 'Request access',
      submitting: 'Submitting…',
      successTitle: 'You\'re on the list.',
      successBody: 'We\'ll review your request and email you an invite code if you\'re a good fit.',
      requestAccessLink: 'Request access',
      invalidEmail: 'Please enter a valid email address.',
      rateLimited: 'You\'ve already requested access recently. Check your inbox or try again tomorrow.',
      submitFailed: 'Could not submit your request. Please try again.',
      // Admin section
      adminTitle: 'Access waitlist',
      adminPending: 'Pending',
      adminApproved: 'Approved',
      adminDeclined: 'Declined',
      adminAll: 'All',
      adminEmpty: 'No requests in this view.',
      adminApprove: 'Approve',
      adminDecline: 'Decline',
      adminCodeGenerated: 'Invite code: {code}',
      adminCopyCode: 'Copy code',
      adminCopiedToast: 'Code copied. Email it to the requester.',
      adminApproveFailed: 'Could not approve. Try again.',
      adminDeclineFailed: 'Could not decline. Try again.',
    },
    onboarding: {
      // Wizard chrome
      stepOf: 'Step {n} of {total}',
      back: 'Back',
      continue: 'Continue',
      skip: 'Skip for now',
      finish: 'Finish',
      // Step 1: Welcome
      welcomeTitle: 'Welcome to Privé',
      welcomeBody: "Let's set up your profile in a few minutes. We'll keep it short — Privé AI helps with the rest.",
      welcomeBegin: 'Begin',
      // Step 2: Photos
      photosTitle: 'Add a photo',
      photosBody: 'At least one photo is required — it\'s the first thing matches see. Add more anytime later.',
      photosUploadBtn: 'Upload a photo',
      photosCounter: '{n} of 9 added',
      // Step 3: Basics
      basicsTitle: 'A few basics',
      basicsBody: "We need these so the right people see you.",
      labelName: 'Your name',
      labelAge: 'Age',
      labelGender: 'I am',
      labelLookingFor: 'Looking for',
      // Step 4: City
      cityTitle: 'Where are you based?',
      cityBody: 'City matters for distance and matching. We only show the city to others — never the exact location.',
      labelCity: 'City',
      labelHometown: 'Hometown (optional)',
      // Step 5: Love Personality quiz (renamed from "Privé code" — 2026-05-22)
      quizTitle: 'Discover your Love Personality',
      quizSubtitle: 'The way you love',
      quizBody: 'Eight quick questions. Your Love Personality lets the AI match you with compatible people.',
      quizQuestionOf: 'Question {n} of {total}',
      quizResultTitle: 'Your Love Personality',
      // Step 6: Bio
      bioTitle: 'A few words about you',
      bioBody: 'Optional but powerful — better bio = better matches. Privé AI can suggest one based on what you\'ve filled in.',
      labelBio: 'Bio',
      bioAiButton: '✨ Let Privé AI suggest a bio',
      bioAiLoading: 'Privé AI is writing…',
      // Step 7: Ready
      readyTitle: "You're ready to discover",
      readyBody: 'Your profile is live. Privé is searching for matches now.',
      readyEnter: 'Enter Privé',
      // Validation errors
      errorNeedPhoto: 'Please add at least one photo.',
      errorNeedName: 'Please tell us your name.',
      errorNeedAge: 'Age must be between 18 and 99.',
      errorNeedCity: 'Please add your city.',
    },
    callToasts: {
      inviteCopied: 'Call invite link copied.',
      copyFailed: 'Copy failed. Please copy the link manually from chat.',
    },
    updateBanner: {
      message: 'A new version is ready.',
      update: 'Update',
      later: 'Later',
      dismiss: 'Dismiss',
    },
    a11y: {
      backToChats: 'Back to chats',
      toggleAiTools: 'Toggle AI tools',
      detectMyLocation: 'Detect my location',
      exitApp: 'Exit App',
      detect: 'Detect',
    },
    photoToasts: {
      editorOpenFailed: 'Unable to open photo editor for this file.',
      uploadFallbackLocal: "Photo saved locally — couldn't upload, will retry on next save.",
      photoUploaded: 'Photo uploaded and added to draft.',
      photoAddedOffline: 'Photo added (offline mode — will sync on next save).',
      processingFailed: 'Photo processing failed. Please try another image.',
    },
    authToasts: {
      accountCreatedConfirmEmail: 'Account created. Confirm your email, then sign in.',
      accountCreatedConfirmEmailToast: 'Account created. Please confirm your email.',
      accountCreatedSuccess: 'Account created successfully.',
      signedInSuccess: 'Signed in successfully.',
      accountCreationFailed: 'Account creation failed.',
      loginFailed: 'Login failed. Check invite code and credentials.',
      guestStarted: 'Guest session started.',
      guestFailed: 'Guest login failed.',
      signOutSyncFailed: 'Sign out sync failed, local session cleared anyway.',
    },
    filters: {
      title: 'Filters',
      zodiacCompatibility: 'Zodiac Compatibility',
      minAge: 'Min Age',
      maxAge: 'Max Age',
      city: 'City',
      interest: 'Interest',
      interestPlaceholder: 'e.g. brunch',
      gender: 'Gender',
      genderWoman: 'Woman',
      genderMan: 'Man',
      genderNonBinary: 'Non-binary',
      lookingFor: 'Looking For',
      goalLongTerm: 'Long-term',
      goalShortTerm: 'Short-term',
      goalFriends: 'Friends',
      goalFiguringItOut: 'Figuring it out',
      maxDistance: 'Max Distance (km)',
      sortBy: 'Sort By',
      sortRecommended: 'Recommended',
      sortNearest: 'Nearest',
      sortYoungest: 'Youngest',
      sortOldest: 'Oldest',
      verifiedOnly: 'Verified Only',
      // AI-first redesign
      aiPromptLabel: 'What are you looking for?',
      aiPromptPlaceholder: 'e.g. someone serious, into hiking, not into clubs…',
      aiPromptHint: 'Privé AI weights matches using this — it\'s not a hard filter.',
      ageRange: 'Age',
      matchCount: 'matches',
      matchCountOne: 'match',
      genderAny: 'Anyone',
      goalAny: 'Any',
      resetAll: 'Reset all',
    },
    common: {
      exitToLogin: 'Exit to Login',
      backToDiscover: 'Back to Discover',
      loading: 'Loading',
      error: 'Error',
      retry: 'Retry',
      noResults: 'No Results',
      reset: 'Reset',
      saveStatus: 'saved',
      selectPlaceholder: 'Select...',
      any: 'Any',
      savingStatus: 'saving',
      idleStatus: 'idle',
      errorStatus: 'error',
    },
    discover: {
      summary: 'Discover summary',
      inDeck: 'In Deck',
      matches: 'Matches',
      likesLeft: 'Likes Left',
      superLikes: 'Super Likes',
      openFilters: 'Open Filters',
      boost: 'Boost',
      resetFilters: 'Reset Filters',
      findingProfiles: 'Finding profiles near you...',
      noProfilesMatch: 'No profiles match your filters',
      upNext: 'Up Next',
      activeNow: 'Active now',
      zodiac: 'Zodiac',
      matchScore: 'Match score',
      personality: 'Personality',
      chemistry: 'Chemistry',
      cognitiveOverlap: 'Cognitive overlap',
      aligned: 'Aligned',
      neutral: 'Neutral',
      viewFullProfile: 'View full profile',
      pass: 'Pass',
      superLike: 'Super Like',
      like: 'Like',
      keyboardShortcuts: 'Keyboard shortcuts',
      undoHint: 'U (undo), Esc (close match).',
      likeLimitReached: 'Like limit reached for your current plan.',
      superLikeLimitReached: 'Super Like limit reached for this week.',
      checkingMatch: 'Checking for a match...',
      lastAction: 'Last action',
      deckComplete: 'Deck Complete',
      noMoreProfiles: 'No more profiles for these filters',
      startAgain: 'Start Again',
      clearHistory: 'Clear History',
      deeperWhyShow: 'Show deeper why',
      deeperWhyHide: 'Hide deeper why',
      frictionPoints: 'Possible friction',
      tips: 'Tips to navigate',
    },
    settings: {
      controlCenter: 'Control Center',
      title: 'Settings',
      subtitle: 'Manage preferences, sharing, notifications, and safety from one polished dashboard.',
      profileSync: 'Profile sync',
      settingsSync: 'Settings sync',
      connectedSocials: 'Connected socials',
      unreadAlerts: 'Unread alerts',
      preferences: 'Preferences',
      pushNotifications: 'Push Notifications',
      emailNotifications: 'Email Notifications',
      appLanguage: 'App Language',
      syncLine: 'Settings: {settings} • Preferences sync: {preferences}',
      socialTitle: 'Social Connect & Share',
      socialConnectedCount: 'Connected: {count} / {total}',
      socialSimpleMode: 'Simple mode: for each platform, just pick Yes or No.',
      socialPromptOptIn: 'Prompt me to share Privé socially',
      socialConnected: 'Connected',
      socialNotConnected: 'Not connected',
      socialConnectAccount: 'Connect this account (Yes)',
      socialShare: 'Share Privé',
      planTitle: 'Plan & Session',
      planLabel: 'Plan',
      planLikesUsed: 'Likes used',
      planSuperLikesUsed: 'Super Likes used',
      planBoostsLeft: 'Boosts left',
      planRewindsLeft: 'Rewinds left',
      planPassportAccess: 'Passport access',
      planEnabled: 'Enabled',
      planUpgradeRequired: 'Upgrade required',
      planUnlimited: 'Unlimited',
      planBackendMode: 'Backend mode',
      planSessionNote: 'Sign out and Exit App live in the top header.',
      notificationsTitle: 'Notifications',
      noNotifications: 'No notifications yet.',
      markAllRead: 'Mark all as read',
      safetyTitle: 'Safety',
      blockedProfiles: 'Blocked profiles',
      reportsSubmitted: 'Reports submitted',
      openReports: 'Open reports',
      noReports: 'No safety reports yet.',
      openModeration: 'Open Moderation Center',
      dangerZone: 'Danger zone',
      deleteAccount: 'Delete my account',
      deleteAccountWarning:
        'This permanently removes your profile, photos, matches, messages, and settings. This cannot be undone.',
      deleteAccountConfirmPrompt: 'Type DELETE to confirm:',
      deleteAccountConfirmWord: 'DELETE',
      deleteAccountConfirmButton: 'Delete forever',
      deleteAccountCancel: 'Cancel',
      deleteAccountDeleting: 'Deleting account...',
      deleteAccountFailed: "Couldn't delete account. Please try again.",
    },
    activity: {
      overview: 'Activity overview',
      liked: 'Liked',
      passed: 'Passed',
      matches: 'Matches',
      noMatchesYet: 'No matches yet.',
      noLikesYet: 'No likes yet.',
      noPassesYet: 'No passes yet.',
      chat: 'Chat',
      view: 'View',
    },
    circles: {
      community: 'Circles community',
      title: 'Circles',
      subtitle: 'Join communities around interests and personality vibes.',
      search: 'Search circles',
      searchPlaceholder: 'Design, travel, coffee...',
      members: 'members',
      joined: 'Joined',
      explore: 'Explore',
      leaveCircle: 'Leave Circle',
      joinCircle: 'Join Circle',
      upcomingEvents: 'Upcoming Events',
      rsvpSaved: 'RSVP Saved',
      rsvp: 'RSVP',
      feed: 'Circle Feed',
      sharePrompt: 'Share something with this circle',
      sharePlaceholder: 'Post a thought, event idea, or question...',
      publishPost: 'Publish Post',
      noPosts: 'No posts yet. Be the first to start the conversation.',
      noCirclesFound: 'No circles found for this search.',
    },
    chats: {
      searchPlaceholder: 'Search conversations...',
      online: 'Online',
      audioCall: 'Audio call',
      videoCall: 'Video call',
      moreOptions: 'More options',
      compatibility: 'Compatibility snapshot',
      type: 'Type',
      zodiac: 'Zodiac',
      cognitive: 'Cognitive',
      unknown: 'Unknown',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      aiCoach: 'AI Date Coach',
      thinking: 'Thinking...',
      generateSuggestions: 'Generate suggestions',
      coachEmpty: 'Generate personalized opener ideas based on your chemistry and recent chat context.',
      aiPlanner: 'AI Date Planner',
      planning: 'Planning...',
      planDate: 'Plan a date',
      useMessage: 'Use this message',
      plannerEmpty: 'Generate 3 personalized date plan options using your shared interests and chemistry.',
      recentCalls: 'Recent Calls',
      videoCallLabel: 'Video call',
      audioCallLabel: 'Audio call',
      rejoin: 'Rejoin',
      openRoom: 'Open room',
      noCallActivity: 'No call activity with this match yet.',
      olderMessages: 'Show {count} older messages',
      joinCall: 'Join call',
      openExternally: 'Open externally',
      attachmentReady: 'Attachment ready:',
      remove: 'Remove',
      typeMessage: 'Type a message...',
      attachMedia: 'Attach media',
      stopRecording: 'Stop recording',
      recordVoice: 'Record voice',
      send: 'Send',
      noChat: 'No Chat',
      selectMatch: 'Select a match to begin chatting',
      closeSuggestions: 'Close suggestions',
      closePlans: 'Close date plans',
      datePlanTonePlayful: 'playful and flirty',
      datePlanToneWarm: 'warm and curious',
      datePlanToneLight: 'light and low-pressure',
      datePlanGoldenTitle: 'Golden Hour Micro-Date',
      datePlanGoldenPlace: '{anchor} + scenic walk',
      datePlanGoldenDuration: '60-90 min',
      datePlanGoldenPitch: 'A {tone} first meetup: a quick {anchor} stop and then a short walk in {city}.',
      datePlanGoldenMessage: 'I have an idea: a {tone} first meetup this week — {anchor} and a short golden-hour walk in {city}. 60-90 minutes, easy vibe. What day works for you?',
      datePlanCultureTitle: 'Culture + Conversation',
      datePlanCulturePlace: 'gallery or museum + {anchorTwo}',
      datePlanCultureDuration: '2-3 hours',
      datePlanCulturePitch: 'A deeper date with conversation moments and shared taste around {anchorTwo}.',
      datePlanCultureMessage: 'Would you be up for a culture date? We could do a gallery/museum stop and then {anchorTwo} after. I think it would fit our vibe really well.',
      datePlanSignatureTitle: 'Signature Night Plan',
      datePlanSignaturePlace: '{anchor} experience + dinner',
      datePlanSignatureDuration: '3-4 hours',
      datePlanSignaturePitch: 'A more curated date flow designed around your chemistry and shared energy.',
      datePlanSignatureMessage: 'I want to plan a proper signature date: start with a {anchor} experience and continue with dinner. If you like, I can send you two concrete options and you pick your favorite.',
    },
    profile: {
      screen: 'Profile screen',
      overview: 'Profile overview',
      aboutMe: 'About Me',
      personalityCode: 'Love Personality',
      lovePersonalitySubtitle: 'The way you love',
      primary: 'Primary',
      support: 'Support',
      tertiary: 'Tertiary',
      shadow: 'Shadow',
      zodiacNote: 'Zodiac note',
      uniqueCosmicSignature: 'Unique cosmic signature.',
      whatCodeMeans: 'What does my Love Personality mean?',
      jobAtCompany: 'at',
      // Zodiac field labels (rendered as <strong> headers in profile detail)
      zodiacOverview: 'overview',
      zodiacLoveStyle: 'Love style',
      zodiacCommunication: 'Communication',
      zodiacGreenFlags: 'Green flags',
      zodiacGrowthEdge: 'Growth edge',
      zodiacEmotionalNeeds: 'Emotional needs',
      zodiacIntimacyStyle: 'Intimacy style',
      zodiacConflictStyle: 'Conflict style',
      zodiacIdealDateEnergy: 'Ideal date energy',
      zodiacBestMatches: 'Best matches',
      // Chemistry panel field labels
      totalChemistry: 'Total chemistry',
      cognitiveOverlap: 'Cognitive overlap',
      // Love Personality guide screen (renamed from "Personality Codes" — 2026-05-22)
      personalityGuide: 'Love Personality Guide',
      personalityGuideSubtitle: 'Understanding your Love Personality',
      personalityCodeExample:
        "Example: DMFR means Decisive, Mindful, Feeling, Reserved. Each letter describes how you naturally love and connect.",
      backToProfile: 'Back to Profile',
      letterMeanings: 'Letter Meanings',
      opposite: 'Opposite',
      allPersonalityTypes: 'All 16 Personality Types',
      thisIsYourType: 'This is your current type.',
      // Match-detail section headers
      whyYouMatchTitle: 'Why you match',
      compatibilityChemistryTitle: 'Compatibility Chemistry',
      cognitiveFunctionsTitle: 'Cognitive Functions',
      zodiacProfileTitle: 'Zodiac Profile',
      zodiacReadingFooter:
        'Complete reading: This sign tends to feel most fulfilled when relationship pacing, emotional language, and daily behavior align with these traits, not just attraction.',
      compatibilityScore: 'Compatibility score',
      personalityFit: 'Personality fit',
      pair: 'Pair',
      type: 'Type',
      defaultEmotionalNeeds: 'Connection, honesty, and safety.',
      defaultIntimacyStyle: 'Expressive and relational.',
      defaultConflictStyle: 'Seeks resolution with care.',
      defaultIdealDateEnergy: 'Balanced and authentic.',
      interests: 'Interests',
      socialTrust: 'Social Trust',
      connectedAccounts: 'Connected accounts',
      noSocialAccounts: 'No social accounts connected yet',
      editProfile: 'Edit My Profile',
      photoCoachTitle: 'AI Photo Coach',
      photoCoachCta: 'Get AI feedback on my photos',
      photoCoachLoading: 'Looking at your photos...',
      photoCoachOverall: 'Overall strategy',
      photoCoachPrimaryPick: 'Recommended primary photo',
      photoCoachPhotoLabel: 'Photo {index}',
      photoCoachScore: 'Score',
      photoCoachStrengths: 'Strengths',
      photoCoachImprovements: 'To improve',
      photoCoachNoPhotos: 'Add at least one photo first.',
      photoCoachError: "Couldn't analyze photos right now. Try again in a moment.",
      photoCoachClose: 'Close',
      photoCoachRetry: 'Try again',
      completenessHeading: 'Profile visibility',
      completenessAllDone: "You're set — your profile is visible in Discover.",
      completenessIntro: "You won't appear in Discover until:",
      completenessName: 'Your name is filled in',
      completenessAge: 'Your age is set (18–99)',
      completenessCity: 'Your city is filled in',
      completenessGender: 'Your gender is selected',
      completenessPhoto: 'You have at least one photo',
      bioWriterCta: 'Improve my bio with AI',
      bioWriterLoading: 'Reading your bio...',
      bioWriterCritiques: 'Notes on your current bio',
      bioWriterRewrites: 'Suggested rewrites',
      bioWriterUseThis: 'Use this',
      bioWriterClose: 'Close',
      bioWriterRetry: 'Try again',
      bioWriterError: "Couldn't generate suggestions right now. Try again in a moment.",
      identity: 'Identity',
      name: 'Name',
      age: 'Age',
      pronouns: 'Pronouns',
      gender: 'Gender',
      orientation: 'Orientation',
      heightCm: 'Height (cm)',
      profileDetails: 'Profile Details',
      city: 'City',
      hometown: 'Hometown',
      vibe: 'Vibe',
      lookingFor: 'Looking For',
      relationshipIntent: 'Relationship Intent',
      interestsComma: 'Interests (comma separated)',
      bio: 'Bio',
      personalityQuiz: 'Love Personality Quiz',
      compatibilityCode: 'Your Love Personality',
      pickOption: 'Pick the option that fits you best.',
      openGuide: 'Open Love Personality guide',
      careerLifestyle: 'Career And Lifestyle',
      jobTitle: 'Job Title',
      company: 'Company',
      education: 'Education',
      languagesComma: 'Languages (comma separated)',
      drinking: 'Drinking',
      smoking: 'Smoking',
      workout: 'Workout',
      pets: 'Pets',
      childrenPlan: 'Children Plan',
      religion: 'Religion',
      politics: 'Politics',
      zodiac: 'Zodiac',
      promptsSocial: 'Prompts And Social',
      prompt1: 'Prompt 1',
      prompt2: 'Prompt 2',
      prompt3: 'Prompt 3',
      dealbreakersComma: 'Dealbreakers (comma separated)',
      instagram: 'Instagram',
      anthem: 'Anthem',
      travelMode: 'Travel Mode',
      photos: 'Photos',
      pastePhotoUrl: 'Paste photo URL',
      addUrl: 'Add URL',
      uploadPhoto: 'Upload photo (opens editor)',
      primaryPhoto: 'Primary',
      setAsPrimary: 'Set as Primary',
    },
  },
  ro: {
    nav: {
      discover: 'Descoperă',
      activity: 'Activitate',
      circles: 'Cercuri',
      chats: 'Mesaje',
      moderation: 'Moderare',
      profile: 'Profil',
      settings: 'Setări',
    },
    auth: {
      signInTitle: 'Intră în Privé',
      createTitle: 'Creează-ți contul Privé',
      inviteCode: 'Cod de invitație',
      invitePlaceholder: 'Introdu codul de invitație',
      email: 'Email',
      password: 'Parolă',
      confirmPassword: 'Confirmă parola',
      passwordHint: 'Minim 10 caractere — literă mare, literă mică, cifră și simbol.',
      pleaseWait: 'Te rugăm să aștepți...',
      createAccount: 'Creează cont',
      signIn: 'Intră în cont',
      continueGuest: 'Continuă ca invitat',
      switchToCreate: 'Creează cont nou',
      switchToLogin: 'Am deja cont',
      language: 'Limba aplicației',
      english: 'Engleză',
      romanian: 'Română',
    },
    waitlist: {
      title: 'Solicită acces',
      subtitle: 'Privé funcționează doar pe invitație. Spune-ne cum te putem contacta.',
      emailLabel: 'Email',
      noteLabel: 'Cum ai aflat de Privé? (opțional)',
      submit: 'Solicită acces',
      submitting: 'Se trimite…',
      successTitle: 'Ești pe listă.',
      successBody: 'Vom analiza cererea ta și îți vom trimite un cod de invitație dacă te potrivești.',
      requestAccessLink: 'Solicită acces',
      invalidEmail: 'Te rugăm introdu o adresă de email validă.',
      rateLimited: 'Ai cerut deja acces recent. Verifică inbox-ul sau încearcă mâine.',
      submitFailed: 'Nu am putut trimite cererea. Te rugăm încearcă din nou.',
      // Secțiune admin
      adminTitle: 'Listă de așteptare',
      adminPending: 'În așteptare',
      adminApproved: 'Aprobate',
      adminDeclined: 'Respinse',
      adminAll: 'Toate',
      adminEmpty: 'Nicio cerere în această vizualizare.',
      adminApprove: 'Aprobă',
      adminDecline: 'Respinge',
      adminCodeGenerated: 'Cod invitație: {code}',
      adminCopyCode: 'Copiază codul',
      adminCopiedToast: 'Codul a fost copiat. Trimite-l pe email solicitantului.',
      adminApproveFailed: 'Aprobarea a eșuat. Mai încearcă.',
      adminDeclineFailed: 'Respingerea a eșuat. Mai încearcă.',
    },
    onboarding: {
      // Cadru asistent
      stepOf: 'Pasul {n} din {total}',
      back: 'Înapoi',
      continue: 'Continuă',
      skip: 'Sări peste',
      finish: 'Termină',
      // Pas 1: Bun venit
      welcomeTitle: 'Bun venit în Privé',
      welcomeBody: 'Hai să-ți configurăm profilul în câteva minute. Îl ținem scurt — Privé AI ajută cu restul.',
      welcomeBegin: 'Începe',
      // Pas 2: Poze
      photosTitle: 'Adaugă o poză',
      photosBody: 'Cel puțin o poză este obligatorie — este primul lucru pe care îl văd potrivirile. Poți adăuga mai multe oricând.',
      photosUploadBtn: 'Încarcă o poză',
      photosCounter: '{n} din 9 adăugate',
      // Pas 3: Detalii
      basicsTitle: 'Câteva detalii',
      basicsBody: 'Avem nevoie de astea ca să te vadă oamenii potriviți.',
      labelName: 'Numele tău',
      labelAge: 'Vârsta',
      labelGender: 'Eu sunt',
      labelLookingFor: 'Caut',
      // Pas 4: Oraș
      cityTitle: 'Unde locuiești?',
      cityBody: 'Orașul contează pentru distanță și potriviri. Afișăm doar orașul altora — niciodată locația exactă.',
      labelCity: 'Oraș',
      labelHometown: 'Oraș natal (opțional)',
      // Pas 5: Personalitatea în iubire (redenumit din „cod Privé" — 2026-05-22)
      quizTitle: 'Descoperă-ți personalitatea în iubire',
      quizSubtitle: 'Felul în care iubești',
      quizBody: 'Opt întrebări rapide. Personalitatea ta în iubire ajută AI-ul să te potrivească cu oameni compatibili.',
      quizQuestionOf: 'Întrebarea {n} din {total}',
      quizResultTitle: 'Personalitatea ta în iubire',
      // Pas 6: Bio
      bioTitle: 'Câteva cuvinte despre tine',
      bioBody: 'Opțional dar puternic — un bio mai bun = potriviri mai bune. Privé AI poate sugera unul pe baza datelor completate.',
      labelBio: 'Bio',
      bioAiButton: '✨ Lasă Privé AI să sugereze un bio',
      bioAiLoading: 'Privé AI scrie…',
      // Pas 7: Gata
      readyTitle: 'Ești gata să descoperi',
      readyBody: 'Profilul tău este activ. Privé caută potriviri pentru tine acum.',
      readyEnter: 'Intră în Privé',
      // Erori validare
      errorNeedPhoto: 'Te rugăm adaugă cel puțin o poză.',
      errorNeedName: 'Te rugăm spune-ne numele tău.',
      errorNeedAge: 'Vârsta trebuie să fie între 18 și 99.',
      errorNeedCity: 'Te rugăm adaugă orașul tău.',
    },
    callToasts: {
      inviteCopied: 'Link-ul de invitație la apel a fost copiat.',
      copyFailed: 'Copierea a eșuat. Te rugăm copiază linkul manual din chat.',
    },
    updateBanner: {
      message: 'O versiune nouă este pregătită.',
      update: 'Actualizează',
      later: 'Mai târziu',
      dismiss: 'Închide',
    },
    a11y: {
      backToChats: 'Înapoi la conversații',
      toggleAiTools: 'Activează/dezactivează unelte AI',
      detectMyLocation: 'Detectează locația mea',
      exitApp: 'Ieși din aplicație',
      detect: 'Detectează',
    },
    photoToasts: {
      editorOpenFailed: 'Editorul de poze nu a putut fi deschis pentru acest fișier.',
      uploadFallbackLocal: 'Poză salvată local — nu s-a putut încărca pe server, vom reîncerca la următoarea salvare.',
      photoUploaded: 'Poza a fost încărcată și adăugată la profil.',
      photoAddedOffline: 'Poză adăugată (mod offline — se va sincroniza la următoarea salvare).',
      processingFailed: 'Procesarea pozei a eșuat. Încearcă o altă imagine.',
    },
    authToasts: {
      accountCreatedConfirmEmail: 'Contul a fost creat. Confirmă email-ul, apoi conectează-te.',
      accountCreatedConfirmEmailToast: 'Contul a fost creat. Te rugăm să confirmi email-ul.',
      accountCreatedSuccess: 'Cont creat cu succes.',
      signedInSuccess: 'Te-ai conectat cu succes.',
      accountCreationFailed: 'Crearea contului a eșuat.',
      loginFailed: 'Conectarea a eșuat. Verifică codul de invitație și datele.',
      guestStarted: 'Sesiune de oaspete pornită.',
      guestFailed: 'Conectarea ca oaspete a eșuat.',
      signOutSyncFailed: 'Sincronizarea deconectării a eșuat; sesiunea locală a fost ștearsă oricum.',
    },
    filters: {
      title: 'Filtre',
      zodiacCompatibility: 'Compatibilitate zodiacală',
      minAge: 'Vârstă minimă',
      maxAge: 'Vârstă maximă',
      city: 'Oraș',
      interest: 'Interes',
      interestPlaceholder: 'ex. brunch',
      gender: 'Gen',
      genderWoman: 'Femeie',
      genderMan: 'Bărbat',
      genderNonBinary: 'Non-binar',
      lookingFor: 'Caut',
      goalLongTerm: 'Pe termen lung',
      goalShortTerm: 'Pe termen scurt',
      goalFriends: 'Prietenie',
      goalFiguringItOut: 'Mă mai gândesc',
      maxDistance: 'Distanță maximă (km)',
      sortBy: 'Sortează după',
      sortRecommended: 'Recomandate',
      sortNearest: 'Cele mai apropiate',
      sortYoungest: 'Cele mai tinere',
      sortOldest: 'Cele mai mature',
      verifiedOnly: 'Doar verificate',
      // Redesign AI-first
      aiPromptLabel: 'Ce cauți?',
      aiPromptPlaceholder: 'ex. cineva serios, pasionat de drumeții, nu de cluburi…',
      aiPromptHint: 'Privé AI ponderează potrivirile pe baza acestui text — nu este un filtru strict.',
      ageRange: 'Vârstă',
      matchCount: 'potriviri',
      matchCountOne: 'potrivire',
      genderAny: 'Oricine',
      goalAny: 'Oricare',
      resetAll: 'Resetează tot',
    },
    common: {
      exitToLogin: 'Înapoi la autentificare',
      backToDiscover: 'Înapoi la Descoperă',
      loading: 'Se încarcă',
      error: 'Eroare',
      retry: 'Încearcă din nou',
      noResults: 'Niciun rezultat',
      reset: 'Resetează',
      saveStatus: 'salvat',
      savingStatus: 'se salvează',
      idleStatus: 'în așteptare',
      errorStatus: 'eroare',
      selectPlaceholder: 'Selectează...',
      any: 'Oricare',
    },
    discover: {
      summary: 'Rezumat descoperire',
      inDeck: 'Disponibili',
      matches: 'Potriviri',
      likesLeft: 'Aprecieri rămase',
      superLikes: 'Super Aprecieri',
      openFilters: 'Filtre',
      boost: 'Boost',
      resetFilters: 'Resetează filtrele',
      findingProfiles: 'Căutăm profile în apropierea ta...',
      noProfilesMatch: 'Niciun profil nu corespunde filtrelor tale',
      upNext: 'Urmează',
      activeNow: 'Activă acum',
      zodiac: 'Zodie',
      matchScore: 'Scor de compatibilitate',
      personality: 'Personalitate',
      chemistry: 'Chimie',
      cognitiveOverlap: 'Suprapunere cognitivă',
      aligned: 'În armonie',
      neutral: 'Neutru',
      viewFullProfile: 'Vezi profilul complet',
      pass: 'Treci',
      superLike: 'Super Apreciere',
      like: 'Apreciere',
      keyboardShortcuts: 'Scurtături tastatură',
      undoHint: 'U (revino), Esc (închide potrivirea).',
      likeLimitReached: 'Ai atins limita de aprecieri pentru planul tău.',
      superLikeLimitReached: 'Ai atins limita de Super Aprecieri pentru săptămâna asta.',
      checkingMatch: 'Verificăm dacă e potrivire...',
      lastAction: 'Ultima acțiune',
      deckComplete: 'Ai văzut tot ce era disponibil',
      noMoreProfiles: 'Nu mai sunt profile care să corespundă filtrelor',
      startAgain: 'Începe din nou',
      clearHistory: 'Șterge istoricul',
      deeperWhyShow: 'Arată detalii mai adânci',
      deeperWhyHide: 'Ascunde detaliile',
      frictionPoints: 'Posibile fricțiuni',
      tips: 'Sfaturi pentru navigare',
    },
    settings: {
      controlCenter: 'Centru de control',
      title: 'Setări',
      subtitle: 'Gestionează preferințele, distribuirea, notificările și siguranța dintr-un singur panou elegant.',
      profileSync: 'Sincronizare profil',
      settingsSync: 'Sincronizare setări',
      connectedSocials: 'Rețele conectate',
      unreadAlerts: 'Alerte necitite',
      preferences: 'Preferințe',
      pushNotifications: 'Notificări push',
      emailNotifications: 'Notificări email',
      appLanguage: 'Limba aplicației',
      syncLine: 'Setări: {settings} • Sincronizare preferințe: {preferences}',
      socialTitle: 'Rețele sociale și distribuire',
      socialConnectedCount: 'Conectate: {count} / {total}',
      socialSimpleMode: 'Mod simplu: pentru fiecare rețea, alegi Da sau Nu.',
      socialPromptOptIn: 'Întreabă-mă să distribui Privé pe rețele',
      socialConnected: 'Conectat',
      socialNotConnected: 'Neconectat',
      socialConnectAccount: 'Conectează acest cont (Da)',
      socialShare: 'Distribuie Privé',
      planTitle: 'Plan și sesiune',
      planLabel: 'Plan',
      planLikesUsed: 'Aprecieri folosite',
      planSuperLikesUsed: 'Super aprecieri folosite',
      planBoostsLeft: 'Boost-uri rămase',
      planRewindsLeft: 'Întoarceri rămase',
      planPassportAccess: 'Acces Passport',
      planEnabled: 'Activ',
      planUpgradeRequired: 'Necesită upgrade',
      planUnlimited: 'Nelimitat',
      planBackendMode: 'Mod backend',
      planSessionNote: 'Deconectarea și ieșirea din aplicație sunt în bara de sus.',
      notificationsTitle: 'Notificări',
      noNotifications: 'Nu ai încă notificări.',
      markAllRead: 'Marchează tot ca citit',
      safetyTitle: 'Siguranță',
      blockedProfiles: 'Profiluri blocate',
      reportsSubmitted: 'Raportări trimise',
      openReports: 'Raportări deschise',
      noReports: 'Nu există încă raportări de siguranță.',
      openModeration: 'Deschide centrul de moderare',
      dangerZone: 'Zonă sensibilă',
      deleteAccount: 'Șterge contul meu',
      deleteAccountWarning:
        'Acțiunea elimină definitiv profilul, pozele, potrivirile, mesajele și setările. Nu poate fi anulată.',
      deleteAccountConfirmPrompt: 'Scrie ȘTERGE pentru a confirma:',
      deleteAccountConfirmWord: 'ȘTERGE',
      deleteAccountConfirmButton: 'Șterge definitiv',
      deleteAccountCancel: 'Anulează',
      deleteAccountDeleting: 'Se șterge contul...',
      deleteAccountFailed: 'Nu s-a putut șterge contul. Mai încearcă.',
    },
    activity: {
      overview: 'Prezentare activitate',
      liked: 'Apreciate',
      passed: 'Respinse',
      matches: 'Potriviri',
      noMatchesYet: 'Nu ai încă potriviri.',
      noLikesYet: 'Nu ai încă aprecieri.',
      noPassesYet: 'Nu ai încă respingeri.',
      chat: 'Chat',
      view: 'Vezi',
    },
    circles: {
      community: 'Comunitatea cercurilor',
      title: 'Cercuri',
      subtitle: 'Intră în comunități construite în jurul intereselor și al vibrației de personalitate.',
      search: 'Caută cercuri',
      searchPlaceholder: 'Design, călătorii, cafea...',
      members: 'membri',
      joined: 'Membru',
      explore: 'Explorează',
      leaveCircle: 'Părăsește cercul',
      joinCircle: 'Alătură-te cercului',
      upcomingEvents: 'Evenimente viitoare',
      rsvpSaved: 'RSVP salvat',
      rsvp: 'RSVP',
      feed: 'Fluxul cercului',
      sharePrompt: 'Spune ceva acestui cerc',
      sharePlaceholder: 'Publică un gând, o idee de eveniment sau o întrebare...',
      publishPost: 'Publică postarea',
      noPosts: 'Nu există încă postări. Fii primul care începe conversația.',
      noCirclesFound: 'Nu au fost găsite cercuri pentru această căutare.',
    },
    chats: {
      searchPlaceholder: 'Caută în conversații...',
      online: 'Activ acum',
      audioCall: 'Apel audio',
      videoCall: 'Apel video',
      moreOptions: 'Mai multe opțiuni',
      compatibility: 'Rezumat compatibilitate',
      type: 'Tip',
      zodiac: 'Zodie',
      cognitive: 'Cognitiv',
      unknown: 'Necunoscut',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      aiCoach: 'Asistent AI pentru conversație',
      thinking: 'Se gândește...',
      generateSuggestions: 'Sugerează mesaje',
      coachEmpty: 'Idei personalizate de început de conversație, pe baza chimiei voastre și a mesajelor recente.',
      aiPlanner: 'Planificator AI de întâlniri',
      planning: 'Se planifică...',
      planDate: 'Planifică o întâlnire',
      useMessage: 'Folosește acest text',
      plannerEmpty: '3 idei personalizate de întâlnire, plecând de la interesele și chimia voastră.',
      recentCalls: 'Apeluri recente',
      videoCallLabel: 'Apel video',
      audioCallLabel: 'Apel audio',
      rejoin: 'Reintră',
      openRoom: 'Deschide camera',
      noCallActivity: 'Niciun apel încă cu această persoană.',
      olderMessages: 'Arată {count} mesaje mai vechi',
      joinCall: 'Intră în apel',
      openExternally: 'Deschide extern',
      attachmentReady: 'Atașament pregătit:',
      remove: 'Elimină',
      typeMessage: 'Scrie un mesaj...',
      attachMedia: 'Atașează un fișier',
      stopRecording: 'Oprește înregistrarea',
      recordVoice: 'Înregistrează o notă vocală',
      send: 'Trimite',
      noChat: 'Nicio conversație',
      selectMatch: 'Alege o potrivire ca să începi conversația',
      closeSuggestions: 'Închide sugestiile',
      closePlans: 'Închide planurile',
      datePlanTonePlayful: 'jucăușă și cochetă',
      datePlanToneWarm: 'caldă și curioasă',
      datePlanToneLight: 'lejeră și fără presiune',
      datePlanGoldenTitle: 'Întâlnire scurtă la apus',
      datePlanGoldenPlace: '{anchor} + plimbare pitorească',
      datePlanGoldenDuration: '60-90 min',
      datePlanGoldenPitch: 'O primă întâlnire {tone}: o oprire scurtă pentru {anchor} și apoi o plimbare scurtă în {city}.',
      datePlanGoldenMessage: 'Am o idee: o primă întâlnire {tone} săptămâna asta — {anchor} și o plimbare scurtă la apus în {city}. 60-90 minute, lejer. Ce zi îți convine?',
      datePlanCultureTitle: 'Cultură și conversație',
      datePlanCulturePlace: 'galerie sau muzeu + {anchorTwo}',
      datePlanCultureDuration: '2-3 ore',
      datePlanCulturePitch: 'O întâlnire mai profundă, cu momente de conversație și gust comun pentru {anchorTwo}.',
      datePlanCultureMessage: 'Ai chef de o întâlnire culturală? Putem trece pe la o galerie sau un muzeu și apoi {anchorTwo}. Cred că s-ar potrivi vibe-ului nostru.',
      datePlanSignatureTitle: 'Plan de seară',
      datePlanSignaturePlace: 'experiență {anchor} + cină',
      datePlanSignatureDuration: '3-4 ore',
      datePlanSignaturePitch: 'O întâlnire mai elaborată, gândită în jurul chimiei și energiei voastre comune.',
      datePlanSignatureMessage: 'Vreau să planific o întâlnire ca lumea: începem cu o experiență {anchor} și continuăm cu o cină. Dacă vrei, îți pot trimite două variante concrete, iar tu alegi.',
    },
    profile: {
      screen: 'Profil',
      overview: 'Prezentare profil',
      aboutMe: 'Despre mine',
      personalityCode: 'Personalitatea ta în iubire',
      lovePersonalitySubtitle: 'Felul în care iubești',
      primary: 'Principal',
      support: 'Auxiliar',
      tertiary: 'Terțiar',
      shadow: 'Umbră',
      zodiacNote: 'Notă zodiacală',
      uniqueCosmicSignature: 'Semnătură cosmică unică.',
      whatCodeMeans: 'Ce înseamnă personalitatea mea în iubire?',
      jobAtCompany: 'la',
      // Etichete câmpuri zodiac
      zodiacOverview: 'pe scurt',
      zodiacLoveStyle: 'Stil în iubire',
      zodiacCommunication: 'Comunicare',
      zodiacGreenFlags: 'Semne bune',
      zodiacGrowthEdge: 'Zonă de creștere',
      zodiacEmotionalNeeds: 'Nevoi emoționale',
      zodiacIntimacyStyle: 'Stil de intimitate',
      zodiacConflictStyle: 'Stil în conflict',
      zodiacIdealDateEnergy: 'Energie ideală la întâlnire',
      zodiacBestMatches: 'Potriviri ideale',
      // Etichete panou chimie
      totalChemistry: 'Chimie totală',
      cognitiveOverlap: 'Suprapunere cognitivă',
      // Ghid Personalitate în iubire (redenumit din „cod" — 2026-05-22)
      personalityGuide: 'Ghid Personalitate în iubire',
      personalityGuideSubtitle: 'Înțelege-ți personalitatea în iubire',
      personalityCodeExample:
        'Exemplu: DMFR înseamnă Decisiv, Mindful, Feeling, Rezervat. Fiecare literă descrie felul în care iubești și creezi conexiuni.',
      backToProfile: 'Înapoi la profil',
      letterMeanings: 'Semnificația literelor',
      opposite: 'Opus',
      allPersonalityTypes: 'Cele 16 tipuri de personalitate',
      thisIsYourType: 'Acesta este tipul tău actual.',
      // Antete secțiuni profil-detaliu
      whyYouMatchTitle: 'De ce vă potriviți',
      compatibilityChemistryTitle: 'Chimia compatibilității',
      cognitiveFunctionsTitle: 'Funcții cognitive',
      zodiacProfileTitle: 'Profil zodiacal',
      zodiacReadingFooter:
        'Lectură completă: acest semn tinde să se simtă cel mai împlinit atunci când ritmul relației, limbajul emoțional și comportamentul de zi cu zi se aliniază cu aceste trăsături, nu doar atracția.',
      compatibilityScore: 'Scor de compatibilitate',
      personalityFit: 'Potrivire de personalitate',
      pair: 'Pereche',
      type: 'Tip',
      defaultEmotionalNeeds: 'Conexiune, onestitate și siguranță.',
      defaultIntimacyStyle: 'Expresiv și relațional.',
      defaultConflictStyle: 'Caută rezolvarea cu grijă.',
      defaultIdealDateEnergy: 'Echilibrat și autentic.',
      interests: 'Interese',
      socialTrust: 'Încredere socială',
      connectedAccounts: 'Conturi conectate',
      noSocialAccounts: 'Nu ai încă niciun cont social conectat',
      editProfile: 'Editează profilul',
      photoCoachTitle: 'Asistent foto AI',
      photoCoachCta: 'Cere o analiză AI a pozelor',
      photoCoachLoading: 'Se analizează pozele...',
      photoCoachOverall: 'Strategie generală',
      photoCoachPrimaryPick: 'Poza recomandată ca principală',
      photoCoachPhotoLabel: 'Poza {index}',
      photoCoachScore: 'Scor',
      photoCoachStrengths: 'Puncte forte',
      photoCoachImprovements: 'De îmbunătățit',
      photoCoachNoPhotos: 'Adaugă întâi cel puțin o poză.',
      photoCoachError: 'Nu s-a putut analiza acum. Mai încearcă în câteva momente.',
      photoCoachClose: 'Închide',
      photoCoachRetry: 'Reîncearcă',
      completenessHeading: 'Vizibilitate profil',
      completenessAllDone: 'Gata — profilul tău e vizibil în Discover.',
      completenessIntro: 'Nu vei apărea în Discover până când:',
      completenessName: 'Ai completat numele',
      completenessAge: 'Ai setat vârsta (18–99)',
      completenessCity: 'Ai completat orașul',
      completenessGender: 'Ai selectat genul',
      completenessPhoto: 'Ai cel puțin o poză',
      bioWriterCta: 'Îmbunătățește bio-ul cu AI',
      bioWriterLoading: 'Se citește bio-ul tău...',
      bioWriterCritiques: 'Observații pe bio-ul actual',
      bioWriterRewrites: 'Variante sugerate',
      bioWriterUseThis: 'Folosește această variantă',
      bioWriterClose: 'Închide',
      bioWriterRetry: 'Reîncearcă',
      bioWriterError: 'Nu s-au putut genera sugestiile. Mai încearcă în câteva momente.',
      identity: 'Identitate',
      name: 'Nume',
      age: 'Vârstă',
      pronouns: 'Pronume',
      gender: 'Gen',
      orientation: 'Orientare',
      heightCm: 'Înălțime (cm)',
      profileDetails: 'Detalii profil',
      city: 'Oraș',
      hometown: 'Oraș natal',
      vibe: 'Vibe',
      lookingFor: 'Caut',
      relationshipIntent: 'Intenția relației',
      interestsComma: 'Interese (separate prin virgulă)',
      bio: 'Bio',
      personalityQuiz: 'Test Personalitate în iubire',
      compatibilityCode: 'Personalitatea ta în iubire',
      pickOption: 'Alege varianta care te descrie cel mai bine.',
      openGuide: 'Deschide ghidul Personalitate în iubire',
      careerLifestyle: 'Carieră și stil de viață',
      jobTitle: 'Funcție',
      company: 'Companie',
      education: 'Educație',
      languagesComma: 'Limbi vorbite (separate prin virgulă)',
      drinking: 'Alcool',
      smoking: 'Fumat',
      workout: 'Sport',
      pets: 'Animale',
      childrenPlan: 'Plan pentru copii',
      religion: 'Religie',
      politics: 'Politică',
      zodiac: 'Zodie',
      promptsSocial: 'Întrebări și social media',
      prompt1: 'Întrebare 1',
      prompt2: 'Întrebare 2',
      prompt3: 'Întrebare 3',
      dealbreakersComma: 'Lucruri intolerabile (separate prin virgulă)',
      instagram: 'Instagram',
      anthem: 'Cântec preferat',
      travelMode: 'Mod călătorie',
      photos: 'Poze',
      pastePhotoUrl: 'Adaugă un link de poză',
      addUrl: 'Adaugă',
      uploadPhoto: 'Încarcă o poză (deschide editorul)',
      primaryPhoto: 'Principală',
      setAsPrimary: 'Setează ca principală',
    },
  },
} as const
/* cSpell:enable */
