export const HISTORY_STORAGE_KEY = 'lovedate:swipe-history'
export const AUTH_STORAGE_KEY = 'lovedate:auth-session'
export const CHAT_THREADS_STORAGE_KEY = 'lovedate:chat-threads'
export const CALL_HISTORY_STORAGE_KEY = 'lovedate:call-history'
export const APP_LANGUAGE_KEY = 'lovedate:app-language'
