export const HISTORY_STORAGE_KEY = 'lovedate:swipe-history'
export const AUTH_STORAGE_KEY = 'lovedate:auth-session'
export const CHAT_THREADS_STORAGE_KEY = 'lovedate:chat-threads'
export const CALL_HISTORY_STORAGE_KEY = 'lovedate:call-history'
export const CIRCLES_JOINED_STORAGE_KEY = 'lovedate:circles-joined'
export const CIRCLES_POSTS_STORAGE_KEY = 'lovedate:circles-posts'
export const CIRCLES_RSVP_STORAGE_KEY = 'lovedate:circles-rsvp'
export const APP_LANGUAGE_KEY = 'lovedate:app-language'
