-- LoveDate beta bootstrap (run once in Supabase SQL editor)
-- Safe to re-run; uses IF NOT EXISTS and idempotent inserts.

create extension if not exists pgcrypto;

create table if not exists public.beta_invites (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

-- Backfill columns for installs predating these fields. `create table if not
-- exists` above is a no-op once the table exists, so columns added later need
-- their own idempotent migration step.
alter table public.beta_invites
  add column if not exists active boolean not null default true,
  add column if not exists expires_at timestamptz;

-- 2026-05-10 — uses_left was never decremented anywhere; dropped in
-- favor of `active` as the single enable/disable flag.
alter table public.beta_invites
  drop column if exists uses_left;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer not null check (age >= 18 and age <= 99),
  city text not null,
  vibe text not null default 'Good energy',
  bio text not null default '',
  interests text[] not null default '{}',
  palette text[] not null default array['#141937', '#252d5c'],
  photos text[] not null default '{}',
  gender text not null check (gender in ('Woman', 'Man', 'Non-binary')),
  distance_km integer not null default 10,
  verified boolean not null default false,
  relationship_goal text not null default 'Long-term'
    check (relationship_goal in ('Long-term', 'Short-term', 'Friends', 'Figuring it out')),
  zodiac text not null default 'Libra',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  push_notifications boolean not null default true,
  email_notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

-- Private/Incognito toggles removed 2026-05-13. Drop the columns so existing
-- deployments stop carrying dead state. Safe to re-run.
alter table public.user_settings
  drop column if exists private_mode,
  drop column if exists incognito_mode;

-- Discovery v1 / Phase B1 — identity bridge from auth.users to public.profiles.
-- A null auth_user_id means a seeded mock profile; a non-null value points
-- to the real user that owns this discoverable row.
alter table public.profiles
  add column if not exists auth_user_id uuid references auth.users (id) on delete cascade;

-- Drop the older partial unique index if it was created by an earlier run.
-- supabase-js .upsert(..., { onConflict: 'auth_user_id' }) needs a full
-- unique constraint as the conflict arbiter; partial indexes don't match.
-- (Multiple NULLs are fine in a UNIQUE constraint, so seeded mock rows with
-- null auth_user_id continue to coexist.)
drop index if exists public.profiles_auth_user_id_key;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_auth_user_id_unique'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_auth_user_id_unique unique (auth_user_id);
  end if;
end$$;

-- Server-side swipe ledger. Currently write-side is not yet wired (Commit B
-- will migrate localStorage history into this table and add the deck filter).
-- Schema lives here now so RLS and constraints are reviewed in the same pass.
create table if not exists public.swipes (
  liker_id uuid not null references auth.users (id) on delete cascade,
  target_id bigint not null references public.profiles (id) on delete cascade,
  direction text not null check (direction in ('right', 'left')),
  created_at timestamptz not null default now(),
  primary key (liker_id, target_id)
);

-- Per-user self-profile (the user's own dating profile, distinct from the
-- public.profiles swipe pool). Stored as JSONB so the schema can evolve
-- without migrations every time we add a field.
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  profile_data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users (id) on delete cascade,
  min_age integer not null default 21,
  max_age integer not null default 39,
  city text not null default '',
  interest text not null default '',
  updated_at timestamptz not null default now()
);

-- 2026-05-11 — include_reviewed was tied to a Filter toggle that caused
-- more friction than it solved. Dropped column for clarity.
alter table public.user_preferences
  drop column if exists include_reviewed;

create table if not exists public.chat_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  match_name text not null,
  outgoing_text text not null,
  generated_reply text not null,
  created_at timestamptz not null default now()
);

alter table public.beta_invites enable row level security;
alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.user_preferences enable row level security;
alter table public.user_profiles enable row level security;
alter table public.chat_events enable row level security;
alter table public.swipes enable row level security;

drop policy if exists "beta_invites_read_active" on public.beta_invites;
create policy "beta_invites_read_active"
on public.beta_invites
for select
to anon, authenticated
using (active = true and (expires_at is null or expires_at > now()));

drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read"
on public.profiles
for select
to anon, authenticated
using (is_active = true);

-- Phase B1: instead of relying on RLS WITH CHECK for inserts (which has
-- edge cases with ON CONFLICT and RETURNING), use a SECURITY DEFINER
-- function that enforces auth.uid() = auth_user_id internally. This is
-- the standard Supabase pattern for upserts that need write access to
-- rows the user does not yet "own" by RLS.
drop policy if exists "profiles_owner_insert" on public.profiles;
drop policy if exists "profiles_owner_update" on public.profiles;

create or replace function public.ensure_discoverable_profile(
  p_name text,
  p_age integer,
  p_city text,
  p_gender text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  insert into public.profiles (auth_user_id, name, age, city, gender, is_active)
  values (v_uid, p_name, p_age, p_city, p_gender, false)
  on conflict (auth_user_id) do update
    set name = excluded.name,
        age = excluded.age,
        city = excluded.city,
        gender = excluded.gender;
end;
$$;

revoke all on function public.ensure_discoverable_profile(text, integer, text, text) from public;
grant execute on function public.ensure_discoverable_profile(text, integer, text, text) to authenticated;

-- Phase B4: full-payload sync function. Replaces the minimum-fields
-- ensure_discoverable_profile from B1 with a richer version that maps the
-- entire discoverable subset of the user's self-profile into public.profiles.
-- Sets is_active=true only when the profile is minimum-viable (name + age +
-- city + valid gender + at least one photo). Below the threshold, the row
-- still exists but stays hidden from everyone's deck.
alter table public.profiles
  add column if not exists extras jsonb not null default '{}'::jsonb;

create or replace function public.sync_discoverable_profile(p_payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text;
  v_age int;
  v_city text;
  v_gender text;
  v_bio text;
  v_vibe text;
  v_interests text[];
  v_photos text[];
  v_distance_km int;
  v_relationship_goal text;
  v_zodiac text;
  v_extras jsonb;
  v_is_active boolean;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  v_name := nullif(trim(coalesce(p_payload->>'name', '')), '');
  v_age := (p_payload->>'age')::int;
  v_city := nullif(trim(coalesce(p_payload->>'city', '')), '');
  v_gender := nullif(coalesce(p_payload->>'gender', ''), '');
  if v_gender not in ('Woman', 'Man', 'Non-binary') then
    v_gender := 'Woman';
  end if;

  v_bio := coalesce(p_payload->>'bio', '');
  v_vibe := coalesce(nullif(trim(coalesce(p_payload->>'vibe', '')), ''), 'Good energy');

  v_interests := coalesce(
    (select array_agg(value) from jsonb_array_elements_text(p_payload->'interests')),
    '{}'::text[]
  );
  v_photos := coalesce(
    (select array_agg(value) from jsonb_array_elements_text(p_payload->'photos')
       where value is not null and length(value) > 0),
    '{}'::text[]
  );

  v_distance_km := greatest(1, coalesce((p_payload->>'distanceKm')::int, 10));
  v_relationship_goal := coalesce(nullif(p_payload->>'relationshipIntent', ''), 'Long-term');
  if v_relationship_goal not in ('Long-term', 'Short-term', 'Friends', 'Figuring it out') then
    v_relationship_goal := 'Long-term';
  end if;
  v_zodiac := coalesce(nullif(p_payload->>'zodiac', ''), 'Libra');

  -- Stash everything the discoverable schema doesn't model directly so we
  -- don't lose data and clients can read it back.
  v_extras := coalesce(p_payload->'extras', '{}'::jsonb);

  -- Skip the upsert entirely if we don't have enough to satisfy NOT NULL
  -- constraints. Caller will retry on next save once more fields are filled.
  if v_name is null or v_age is null or v_age < 18 or v_age > 99 or v_city is null then
    return;
  end if;

  -- Minimum-viable check for visibility in the deck.
  v_is_active := array_length(v_photos, 1) is not null and array_length(v_photos, 1) >= 1;

  insert into public.profiles (
    auth_user_id, name, age, city, gender, vibe, bio, interests,
    photos, distance_km, relationship_goal, zodiac, extras, is_active
  )
  values (
    v_uid, v_name, v_age, v_city, v_gender, v_vibe, v_bio, v_interests,
    v_photos, v_distance_km, v_relationship_goal, v_zodiac, v_extras, v_is_active
  )
  on conflict (auth_user_id) do update
    set name = excluded.name,
        age = excluded.age,
        city = excluded.city,
        gender = excluded.gender,
        vibe = excluded.vibe,
        bio = excluded.bio,
        interests = excluded.interests,
        photos = excluded.photos,
        distance_km = excluded.distance_km,
        relationship_goal = excluded.relationship_goal,
        zodiac = excluded.zodiac,
        extras = excluded.extras,
        is_active = excluded.is_active;
end;
$$;

revoke all on function public.sync_discoverable_profile(jsonb) from public;
grant execute on function public.sync_discoverable_profile(jsonb) to authenticated;

-- Defensive: keep any legacy mock-profile rows hidden from the deck. The
-- seed INSERT below was removed because it had no unique constraint to
-- key on and created duplicates on every SQL re-run (~2 new rows per run).
-- If you need mock profiles for demos, insert them manually with explicit
-- ids via the SQL editor.
update public.profiles set is_active = false where auth_user_id is null;

-- Private/Incognito toggles removed 2026-05-13. The visibility helper and
-- its RLS policy override are gone; the simple `profiles_public_read using
-- (is_active = true)` policy defined earlier in this file is the final
-- read gate. Drop the helper if a previous run created it.
drop function if exists public.is_profile_visible_to_me(bigint);

drop policy if exists "user_settings_owner_select" on public.user_settings;
create policy "user_settings_owner_select"
on public.user_settings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_settings_owner_upsert" on public.user_settings;
create policy "user_settings_owner_upsert"
on public.user_settings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_settings_owner_update" on public.user_settings;
create policy "user_settings_owner_update"
on public.user_settings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_preferences_owner_select" on public.user_preferences;
create policy "user_preferences_owner_select"
on public.user_preferences
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_preferences_owner_upsert" on public.user_preferences;
create policy "user_preferences_owner_upsert"
on public.user_preferences
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_preferences_owner_update" on public.user_preferences;
create policy "user_preferences_owner_update"
on public.user_preferences
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_profiles_owner_select" on public.user_profiles;
create policy "user_profiles_owner_select"
on public.user_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_profiles_owner_insert" on public.user_profiles;
create policy "user_profiles_owner_insert"
on public.user_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_profiles_owner_update" on public.user_profiles;
create policy "user_profiles_owner_update"
on public.user_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "chat_events_owner_select" on public.chat_events;
create policy "chat_events_owner_select"
on public.chat_events
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "chat_events_owner_insert" on public.chat_events;
create policy "chat_events_owner_insert"
on public.chat_events
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "swipes_owner_select" on public.swipes;
create policy "swipes_owner_select"
on public.swipes
for select
to authenticated
using (auth.uid() = liker_id);

drop policy if exists "swipes_owner_insert" on public.swipes;
create policy "swipes_owner_insert"
on public.swipes
for insert
to authenticated
with check (auth.uid() = liker_id);

drop policy if exists "swipes_owner_delete" on public.swipes;
create policy "swipes_owner_delete"
on public.swipes
for delete
to authenticated
using (auth.uid() = liker_id);

-- Phase B3: server-side block list. Each row records that user_id has
-- blocked blocked_profile_id (a public.profiles row). Owner-only RLS so
-- the list is private. Backfilled lazily from each device's localStorage
-- on first authed load, after which the cloud list is authoritative.
create table if not exists public.user_blocks (
  user_id uuid not null references auth.users (id) on delete cascade,
  blocked_profile_id bigint not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, blocked_profile_id)
);

alter table public.user_blocks enable row level security;

drop policy if exists "user_blocks_owner_select" on public.user_blocks;
create policy "user_blocks_owner_select"
on public.user_blocks
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_blocks_owner_insert" on public.user_blocks;
create policy "user_blocks_owner_insert"
on public.user_blocks
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_blocks_owner_delete" on public.user_blocks;
create policy "user_blocks_owner_delete"
on public.user_blocks
for delete
to authenticated
using (auth.uid() = user_id);

-- Phase C2 — Safety reports to cloud.
--
-- Until now, submitProfileReport wrote to a localStorage queue only. A
-- reported user was invisible to the operator unless they happened to log
-- in on the reporter's own device. This block adds a cloud table so reports
-- are durable and admin-readable.
--
-- Schema notes:
--   - reporter_id / reported_profile_id are `on delete set null` so the
--     audit trail survives account deletion on either side. profile_snapshot
--     keeps the data even if the profile row is later gone.
--   - status mirrors the client-side ModerationStatus enum.
create table if not exists public.safety_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid references auth.users (id) on delete set null,
  reported_profile_id bigint references public.profiles (id) on delete set null,
  profile_snapshot jsonb not null default '{}'::jsonb,
  category text not null
    check (category in ('spam','scam','harassment','hate','nudity','underage','impersonation','other')),
  details text not null default '',
  status text not null default 'open'
    check (status in ('open','reviewing','resolved','dismissed')),
  reviewed_at timestamptz,
  reviewer_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists safety_reports_status_created_idx
  on public.safety_reports (status, created_at desc);
create index if not exists safety_reports_reporter_idx
  on public.safety_reports (reporter_id);

alter table public.safety_reports enable row level security;

-- Admin identity helper. Keep the email allowlist in sync with the
-- VITE_MODERATION_ADMIN_EMAILS fallback in App.tsx. When we move to a
-- server-side admin role, replace this body with a role-table lookup.
create or replace function public.is_admin()
returns boolean
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_email text;
begin
  select email into v_email from auth.users where id = auth.uid();
  if v_email is null then
    return false;
  end if;
  return lower(v_email) in ('viomediere@gmail.com', 'viorelbox1@gmail.com');
end;
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "safety_reports_owner_insert" on public.safety_reports;
create policy "safety_reports_owner_insert"
on public.safety_reports
for insert
to authenticated
with check (
  auth.uid() = reporter_id
  and reported_profile_id is not null
);

drop policy if exists "safety_reports_owner_select" on public.safety_reports;
create policy "safety_reports_owner_select"
on public.safety_reports
for select
to authenticated
using (auth.uid() = reporter_id);

drop policy if exists "safety_reports_admin_select" on public.safety_reports;
create policy "safety_reports_admin_select"
on public.safety_reports
for select
to authenticated
using (public.is_admin());

drop policy if exists "safety_reports_admin_update" on public.safety_reports;
create policy "safety_reports_admin_update"
on public.safety_reports
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Phase C3 — Chat to cloud.
--
-- Until now, chatThreads in App.tsx lived in localStorage; two friends on
-- two phones could never see each other's messages. This block adds a real
-- messaging primitive.
--
-- Pair identity: messages travel between auth.uid() (sender_id) and the
-- other user's auth.uid() (recipient_id). RLS lets either participant
-- read; only the sender can insert, and only if they are matched (both
-- right-swiped each other in public.swipes).
--
-- Realtime: chat_messages is added to the supabase_realtime publication so
-- the client can subscribe to inserts.
create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users (id) on delete cascade,
  recipient_id uuid not null references auth.users (id) on delete cascade,
  text text not null default '',
  attachment jsonb,
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create index if not exists chat_messages_recipient_created_idx
  on public.chat_messages (recipient_id, created_at desc);
create index if not exists chat_messages_sender_created_idx
  on public.chat_messages (sender_id, created_at desc);

alter table public.chat_messages enable row level security;

-- Match check: both users have right-swiped each other's profile row.
-- SECURITY DEFINER so it can read the swipes table (which is owner-RLS'd
-- to liker_id) for both sides of the pair.
create or replace function public.users_are_matched(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.swipes s
    join public.profiles p on p.id = s.target_id
    where s.liker_id = user_a
      and s.direction = 'right'
      and p.auth_user_id = user_b
  ) and exists (
    select 1 from public.swipes s
    join public.profiles p on p.id = s.target_id
    where s.liker_id = user_b
      and s.direction = 'right'
      and p.auth_user_id = user_a
  );
$$;

revoke all on function public.users_are_matched(uuid, uuid) from public;
grant execute on function public.users_are_matched(uuid, uuid) to authenticated;

drop policy if exists "chat_messages_participant_select" on public.chat_messages;
create policy "chat_messages_participant_select"
on public.chat_messages
for select
to authenticated
using (
  auth.uid() = sender_id
  or auth.uid() = recipient_id
);

drop policy if exists "chat_messages_sender_insert" on public.chat_messages;
create policy "chat_messages_sender_insert"
on public.chat_messages
for insert
to authenticated
with check (
  auth.uid() = sender_id
  and public.users_are_matched(sender_id, recipient_id)
);

-- Add chat_messages to the realtime publication so the client can subscribe.
-- Wrapped in a check because supabase_realtime is created by the platform
-- and may not exist in a fresh self-hosted setup.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'chat_messages'
    ) then
      execute 'alter publication supabase_realtime add table public.chat_messages';
    end if;
  end if;
end$$;

-- Phase B2: Supabase Storage bucket for profile photos. Public read so any
-- viewer can render deck cards without an extra signed-URL roundtrip; writes
-- restricted to authenticated users uploading into their own auth-uid folder.
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "profile_photos_public_read" on storage.objects;
create policy "profile_photos_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'profile-photos');

drop policy if exists "profile_photos_owner_insert" on storage.objects;
create policy "profile_photos_owner_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "profile_photos_owner_update" on storage.objects;
create policy "profile_photos_owner_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "profile_photos_owner_delete" on storage.objects;
create policy "profile_photos_owner_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

insert into public.beta_invites (code, active, expires_at)
values
  ('LOVE-BETA-001', true, now() + interval '90 days'),
  ('LOVE-BETA-TEAM', true, now() + interval '365 days')
on conflict (code) do update
set active = excluded.active,
    expires_at = excluded.expires_at;

-- Seed mock-profile INSERT removed 2026-05-11. It had no unique key to
-- conflict on, so every re-run of this file produced a fresh duplicate of
-- each row. Existing duplicates should be deleted manually with:
--   delete from public.profiles where auth_user_id is null;
-- Real users now drive the discover deck (Phase B4 onward).
